<?php $this->flashSession->output(); ?>
<div id='map-canvas'></div>


<hr/>

<h1>Info da Rota</h1>

<?php if (isset($route_info)): ?>
	<?php echo "Route id: ", $route_info->id, "<br>"; ?>
	<?php echo "Route title: ", $route_info->title, "<br>"; ?>
	<?php echo "Route description: ", $route_info->description, "<br>"; ?>
	<?php echo "User's route: ", $route_info->users->username, "<br>"; ?>
	<?php echo "Route number of likes: ", $route_info->number_of_likes, "<br>"; ?>
	<?php echo "Route datetime created: ", $route_info->datetime_created, "<br>"; ?>
<?php endif ?>


<h1>Polaroids da Rota</h1>

<?php foreach ($route_polaroids as $route_polaroid): ?>
	<hr/>
	<?php echo $route_polaroid->id_polaroid; ?> <br/>
	<?php echo $route_polaroid->polaroids->lat; ?> <br/>
	<?php echo $route_polaroid->polaroids->lon; ?> <br/>
	<?php echo $route_polaroid->polaroids->title; ?> <br/>
	<?php echo $route_polaroid->polaroids->description; ?> <br/>
	<?php echo $route_polaroid->polaroids->photo_hash_file_name; ?> <br/>
	<?php echo $route_polaroid->datetime_associated; ?> <br/>
<?php endforeach ?>


<script>
	window.onload = function () {

		var data = [

			    <?php foreach ($route_polaroids as $route_polaroid): ?>
					<?php echo "{"; ?>
					    <?php echo "lat: " . $route_polaroid->polaroids->lat.",";?>
					    <?php echo "lon: " . $route_polaroid->polaroids->lon.","; ?>
					    <?php echo "title: '".$route_polaroid->polaroids->title . "',"; ?>
					    <?php echo "stopover: true"; ?>
				    <?php echo "},"; ?>
			    <?php endforeach ?>
		];


		new Maplace({
			locations         : data,
			map_div           : '#map-canvas',
			controls_div      : false,
			generate_controls : false,
			show_markers      : false,
			type              : 'directions',
			draggable         : false,
			// directions_panel  : '#route',
			listeners: {
				click: function (marker, event) {
					console.log(marker);
					alert("Bye" + marker);
				}
			}
		}).Load();


		$(window).resize(function () {

			var height = $(window).height();
			var width = $(window).width();
			var nheight = (height - (0.1 * height)) + 'px';
			var nwidth = (width - (0.4 * width)) + 'px';
			$('#gmap-route').css({
				width: nwidth,
				height: nheight
			});
		}).resize();

	};
</script>
