<?php $this->flashSession->output(); ?>

<div class="large-8 columns panel">
	<ul class="tabs" data-tab>
		<li class="tab-title active"><a href="#panel1">Route Map</a></li>
		<li class="tab-title"><a href="#panel2">Directions</a></li>
	</ul>
	<div class="tabs-content">
		<div class="content active panel" id="panel1">
			<div style="margin: 0 auto;" id='gmap-route' class="large-8" ></div>
		</div>
		<div class="content" id="panel2">
			<div id="route"></div>
		</div>
	</div>
</div>
<div class="large-4 columns panel">
	<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet aspernatur consectetur doloribus eum necessitatibus nesciunt obcaecati quos, recusandae sunt voluptas? Culpa dicta id in maxime non recusandae voluptate? Iure, voluptate?</p>
</div>


<hr/>

<h1>Info da Rota</h1>

<?php if (isset($route_info)): ?>
	<?php echo "Route id: ", $route_info->id, "<br>"; ?>
	<?php echo "Route title: ", $route_info->title, "<br>"; ?>
	<?php echo "Route description: ", $route_info->description, "<br>"; ?>
	<?php echo "User's route: ", $route_info->users->username, "<br>"; ?>
	<?php echo "Route number of likes: ", $route_info->number_of_likes, "<br>"; ?>
	<?php echo "Route datetime created: ", $route_info->datetime_created, "<br>"; ?>
<?php endif ?>


<h1>Polaroids da Rota</h1>

<?php foreach ($route_polaroids as $route_polaroid): ?>
	<hr/>
	<?php echo $route_polaroid->id_polaroid; ?> <br/>
	<?php echo $route_polaroid->polaroids->lat; ?> <br/>
	<?php echo $route_polaroid->polaroids->lon; ?> <br/>
	<?php echo $route_polaroid->polaroids->title; ?> <br/>
	<?php echo $route_polaroid->polaroids->description; ?> <br/>
	<?php echo $route_polaroid->polaroids->photo_hash_file_name; ?> <br/>
	<?php echo $route_polaroid->datetime_associated; ?> <br/>
<?php endforeach ?>


<script>
	window.onload = function () {

		var data = [

			    <?php foreach ($route_polaroids as $route_polaroid): ?>
					<?php echo "{"; ?>
					    <?php echo "lat: " . $route_polaroid->polaroids->lat.",";?>
					    <?php echo "lon: " . $route_polaroid->polaroids->lon.","; ?>
					    <?php echo "title: '".$route_polaroid->polaroids->title . "',"; ?>
					    <?php echo "stopover: true"; ?>
				    <?php echo "},"; ?>
			    <?php endforeach ?>
		];


		new Maplace({
			locations         : data,
			map_div           : '#gmap-route',
			controls_div      : false,
			generate_controls : false,
			show_markers      : false,
			type              : 'directions',
			draggable         : false,
			directions_panel  : '#route',
			listeners: {
				click: function (marker, event) {
					console.log(marker);
					alert("Bye" + marker);
				}
			}
		}).Load();


		$(window).resize(function () {

			var height = $(window).height();
			var width = $(window).width();
			var nheight = (height - (0.1 * height)) + 'px';
			var nwidth = (width - (0.4 * width)) + 'px';
			$('#gmap-route').css({
				width: nwidth,
				height: nheight
			});
		}).resize();

	};
</script>
