<ul class="off-canvas-list">
	<li><label>Last Places</label></li>
	<li data-lat="37.427474" data-lon="-122.169719"
	    class="ajax-change-last-place"><a href="">The Psychohistorians</a></li>
	<li data-lat="37.427474" data-lon="-122.169719"
	    class="ajax-change-last-place"><a href="">The Mayors</a></li>
	<li data-lat="37.427474" data-lon="-122.169719"
	    class="ajax-change-last-place"><a href="">The Traders</a></li>
	<li data-lat="37.427474" data-lon="-122.169719"
	    class="ajax-change-last-place"><a href="">The Merchant Princes</a></li>
	<li data-lat="37.427474" data-lon="-122.169719"
	    class="ajax-change-last-place"><a href="">The General</a></li>

	<li><label>Last Routes</label></li>

	<li class="ajax-change-last-route"><a href="">The Psychohistorians</a></li>
	<li class="ajax-change-last-route"><a href="">The Encyclopedists</a></li>
	<li class="ajax-change-last-route"><a href="">The Mayors</a></li>
	<li class="ajax-change-last-route"><a href="">The Merchant Princes</a></li>
	<li class="ajax-change-last-route"><a href="">The General</a></li>
	<li class="ajax-change-last-route"><a href="">The Mule</a></li>
	<li class="ajax-change-last-route"><a href="">Search by the Mule</a></li>


	<li><label>Most Liked Polaroids</label></li>
	<li class="ajax-change-last-like">
		<a href="">The Psychohistorians</a>
	</li>
	<li class="ajax-change-last-like">
		<a href="">The Encyclopedists</a>
	</li>
	<li class="ajax-change-last-like">
		<a href="">The Mayors</a>
	</li>
	<li class="ajax-change-last-like">
		<a href="">The Merchant Princes</a>
	</li>
</ul>
