<aside class="right-off-canvas-menu">
	<ul class="off-canvas-list">
		<li><label><?php echo $logged_user->full_name; ?></label></li>
		<li>
			<a style="border: 1px solid rgb(38, 38, 38);
						text-align: center;"
			   class="th radius"
			   href="<?php echo $this->url->get("/my-profile"); ?>">
				<img height="96" width="96"
				     src="http://www.gravatar.com/avatar/<?php
					     echo md5(strtolower(trim($logged_user->email)));?>?s=96">
			</a>
		</li>
		<br/><br/>
		<li style="border-top: 1px solid #262626;"
		    class="text-center"><?php echo $this->tag->linkTo("/my-profile", 'My Profile <i style="margin-left: 12px;" class="fi-price-tag app-icons"></i>'); ?></li>
		<li class="text-center"><?php echo $this->tag->linkTo("/my-places", 'My Polaroids <i style="margin-left: 14px;"  class="fi-marker app-icons"></i>'); ?>
		</li>
		<li class="text-center"><?php echo $this->tag->linkTo("/my-routes", 'My Routes <i class="fi-map app-icons"></i>'); ?></li>
		<li class="text-center"><?php echo $this->tag->linkTo("/i-liked", 'I Liked <i class="fi-like app-icons"></i>'); ?></li>
<!--		<li style="border-top: 1px solid #262626;"-->
<!--		    class="text-center">--><?php //echo $this->tag->linkTo("find", 'Find <i class="fi-magnifying-glass app-icons"></i>'); ?><!--</li>-->
		<li class="text-center"><?php echo $this->tag->linkTo("/i-am-following", 'I am Following <i class="fi-torsos-all-female app-icons"></i>'); ?></li>
		<li class="text-center"><?php echo $this->tag->linkTo("/my-account", 'Manage Account <i class="fi-widget app-icons"></i>'); ?></li>

		<br/><br/><br/>
		<li style="border-top: 1px solid #262626;"
		    class="text-center"><?php echo $this->tag->linkTo("/logout", 'Logout <i class="fi-shuffle app-icons"></i>'); ?></li>
	</ul>
</aside>
