<h1 class="headers-provisorios">FindController - allAction</h1>

<?php $this->flashSession->output(); ?>

<div class="">
	<ul class="example-orbit-content" data-orbit data-options="bullets:false;
	slide_number:false;pause_on_hover:false;animation:'fade';
	timer_speed:4000;navigation_arrows:false;">
		<li data-orbit-slide="headline-1">
			<div class=" text-center small-12 columns">
				<a class="th" href="#">
					<img src="http://placehold.it/100x100&amp;text=User x">
				</a>
				<a class="th" href="#">
					<img src="http://placehold.it/100x100&amp;text=User x">
				</a>
				<a class="th" href="#">
					<img src="http://placehold.it/100x100&amp;text=User x">
				</a>
				<a class="th" href="#">
					<img src="http://placehold.it/100x100&amp;text=User x">
				</a>
				<a class="th" href="#">
					<img src="http://placehold.it/100x100&amp;text=User x">
				</a>
				<a class="th" href="#">
					<img src="http://placehold.it/100x100&amp;text=User x">
				</a>
				<a class="th" href="#">
					<img src="http://placehold.it/100x100&amp;text=User x">
				</a>
				<a class="th" href="#">
					<img src="http://placehold.it/100x100&amp;text=User x">
				</a>
				<a class="th" href="#">
					<img src="http://placehold.it/100x100&amp;text=User x">
				</a>
				<a class="th" href="#">
					<img src="http://placehold.it/100x100&amp;text=User x">
				</a>
				<a class="th" href="#">
					<img src="http://placehold.it/100x100&amp;text=User x">
				</a>
				<a class="th" href="#">
					<img src="http://placehold.it/100x100&amp;text=User x">
				</a>
			</div>
		</li>
		<li data-orbit-slide="headline-2">
			<div class=" text-center small-12 columns">
				<a class="th" href="#">
					<img src="http://placehold.it/100x100&amp;text=Polaroids x">
				</a>
				<a class="th" href="#">
					<img src="http://placehold.it/100x100&amp;text=Polaroids x">
				</a>
				<a class="th" href="#">
					<img src="http://placehold.it/100x100&amp;text=Polaroids x">
				</a>
				<a class="th" href="#">
					<img src="http://placehold.it/100x100&amp;text=Polaroids x">
				</a>
				<a class="th" href="#">
					<img src="http://placehold.it/100x100&amp;text=Polaroids x">
				</a>
				<a class="th" href="#">
					<img src="http://placehold.it/100x100&amp;text=Polaroids x">
				</a>
				<a class="th" href="#">
					<img src="http://placehold.it/100x100&amp;text=Polaroids x">
				</a>
				<a class="th" href="#">
					<img src="http://placehold.it/100x100&amp;text=Polaroids x">
				</a>
				<a class="th" href="#">
					<img src="http://placehold.it/100x100&amp;text=Polaroids x">
				</a>
				<a class="th" href="#">
					<img src="http://placehold.it/100x100&amp;text=Polaroids x">
				</a>
				<a class="th" href="#">
					<img src="http://placehold.it/100x100&amp;text=Polaroids x">
				</a>
				<a class="th" href="#">
					<img src="http://placehold.it/100x100&amp;text=Polaroids x">
				</a>
			</div>
		</li>
		</li>
		<li data-orbit-slide="headline-3">
			<div class=" text-center small-12 columns">
				<a class="th" href="#">
					<img src="http://placehold.it/100x100&amp;text=Route x">
				</a>
				<a class="th" href="#">
					<img src="http://placehold.it/100x100&amp;text=Route x">
				</a>
				<a class="th" href="#">
					<img src="http://placehold.it/100x100&amp;text=Route x">
				</a>
				<a class="th" href="#">
					<img src="http://placehold.it/100x100&amp;text=Route x">
				</a>
				<a class="th" href="#">
					<img src="http://placehold.it/100x100&amp;text=Route x">
				</a>
				<a class="th" href="#">
					<img src="http://placehold.it/100x100&amp;text=Route x">
				</a>
				<a class="th" href="#">
					<img src="http://placehold.it/100x100&amp;text=Route x">
				</a>
				<a class="th" href="#">
					<img src="http://placehold.it/100x100&amp;text=Route x">
				</a>
				<a class="th" href="#">
					<img src="http://placehold.it/100x100&amp;text=Route x">
				</a>
				<a class="th" href="#">
					<img src="http://placehold.it/100x100&amp;text=Route x">
				</a>
				<a class="th" href="#">
					<img src="http://placehold.it/100x100&amp;text=Route x">
				</a>
				<a class="th" href="#">
					<img src="http://placehold.it/100x100&amp;text=Route x">
				</a>
			</div>
		</li>
		</li>
	</ul>
</div>

<div class="row panel">
	<div class="large-12 columns">
		<form action="<?php echo $this->url->get("/find/all"); ?>" method="get">
			<div class="row collapse">
				<div class="large-10 small-8 columns">
					<input style="height: 3.8em;" type="text" name="q" value="<?php
						echo isset($searched_query) ? $searched_query : "";
					?>">
				</div>
				<div class="large-2 small-3 columns">
					<input class="button" type="submit" value="Search"/>
				</div>
			</div>
		</form>
	</div>
</div>

<?php if (isset($searched_query) && $searched_query != ""): ?>

	<div class="row text-center">
		<div class="large-12 columns">
			<h2>Results:</h2>
			<ul class="small-block-grid-3">
				<li>
					<a href="<?php echo $this->url->get("/find/users/". $searched_query);?>">
						<img class="th" src="http://placehold.it/250x250&amp;text=2312653 Users">
						<h4><?php echo isset($num_users) ? $num_users : "";?></h4>
					</a>

				</li>
				<li>
					<a href="<?php echo $this->url->get("/find/polaroids/" . $searched_query); ?>">
						<img class="th" src="http://placehold.it/250x250&amp;text=23434 Polaroids">
						<h4><?php echo isset($num_polaroids) ? $num_polaroids : "";?></h4>
					</a>

				</li>
				<li>
					<a href="<?php echo $this->url->get("/find/routes/" . $searched_query); ?>">
						<img class="th" src="http://placehold.it/250x250&amp;text=17698 Routes">
						<h4><?php echo isset($num_routes) ? $num_routes : "";?></h4>
					</a>
				</li>

			</ul>
		</div>
	</div>

<?php else: ?>

	<div class="row text-center">
		<div class="large-12 columns">
			<h2>Results:</h2>
			<ul class="small-block-grid-3">
				<li>
					<a href="<?php echo $this->url->get("/find-users/"); ?>">
						<img class="th"
						     src="http://placehold.it/250x250&amp;text=2312653 Users">
						<h4><?php echo isset($num_users) ? $num_users : ""; ?></h4>
					</a>

				</li>
				<li>
					<a href="<?php echo $this->url->get("/find-polaroids/"); ?>">
						<img class="th"
						     src="http://placehold.it/250x250&amp;text=23434 Polaroids">
						<h4><?php echo isset($num_polaroids) ? $num_polaroids : ""; ?></h4>
					</a>

				</li>
				<li>
					<a href="<?php echo $this->url->get("/find-routes/"); ?>">
						<img class="th"
						     src="http://placehold.it/250x250&amp;text=17698 Routes">
						<h4><?php echo isset($num_routes) ? $num_routes : ""; ?></h4>
					</a>
				</li>

			</ul>
		</div>
	</div>
<?php endif ?>


