<?php $this->flashSession->output(); ?>

<ul class="breadcrumbs">
	<li><a href="<?php echo $this->url->get("/find"); ?>">Find</a></li>
	<li class="current"><a href="<?php echo $this->url->get
		("/find-polaroids"); ?>">Find All Polaroids</a></li>
</ul>


<?php foreach ($page->items as $item): ?>
	<ul>
		<li><?php echo $item->id; ?></li>
		<li><?php echo $item->title; ?></li>
		<li><?php echo $item->description; ?></li>
		<li><?php echo $item->photo_hash_file_name; ?></li>
		<li><?php echo $item->number_of_likes; ?></li>
		<li><?php echo $item->country; ?></li>
		<li><?php echo $item->id_user; ?></li>
		<li><?php echo $item->users->username; ?></li>
	</ul>
<?php endforeach ?>

<ul class="pagination" role="menubar" aria-label="Pagination">
	<?php if ($page->current != $page->first): ?>
		<li>
			<a href="<?php echo $this->url->get("/find-polaroids");?>">First</a>
		</li>
		<li class="arrow"><a
				href="<?php echo $this->url->get("/find-polaroids/" . $page->before);?>">&laquo;
				Previous</a></li>
	<?php endif ?>

	<li class="current"><a href=""><?php echo $page->current; ?></a></li>
	<li class="unavailable" aria-disabled="true"><a href="">&hellip;
			of <?php echo $page->total_items; ?></a></li>

	<?php if ($page->current != $page->last): ?>
		<li class="arrow"><a
				href="<?php echo $this->url->get("/find-polaroids/" . $page->next);?>">Next &raquo;</a>
		</li>
		<li>
			<a href="<?php echo $this->url->get("/find-polaroids/" . $page->last);?>">Last</a>
		</li>
	<?php endif ?>

</ul>
