<h1 class="headers-provisorios">FindController - allRoutesAction</h1>

<?php $this->flashSession->output(); ?>

<?php foreach ($page->items as $item): ?>
	<ul>
		<li><?php echo $item->id; ?></li>
		<li><?php echo $item->title; ?></li>
		<li><?php echo $item->description; ?></li>
		<li><?php echo $item->number_of_likes; ?></li>
		<li><?php echo $item->id_user; ?></li>
		<li><?php echo $item->users->username; ?></li>
	</ul>
<?php endforeach ?>


<?php echo $this->tag->linkTo("/find-routes/", "First") . " | "; ?>
<?php echo $this->tag->linkTo("/find-routes/". $page->before, "Previous") . " | "; ?>
<?php echo $this->tag->linkTo("/find-routes/". $page->next, "Next") . " | "; ?>
<?php echo $this->tag->linkTo("/find-routes/". $page->last, "Last"); ?>

<br/><br/>
<?php echo "You are in page ", $page->current, " of ", $page->total_pages; ?>
<br/>
<?php echo "There are a total of items of ", $page->total_items; ?>
