<h1 class="headers-provisorios">FindController - allRoutesAction</h1>

<?php $this->flashSession->output(); ?>

<?php foreach ($page->items as $item): ?>
	<ul>
		<li><?php echo $item->id; ?></li>
		<li><?php echo $item->title; ?></li>
		<li><?php echo $item->description; ?></li>
		<li><?php echo $item->number_of_likes; ?></li>
		<li><?php echo $item->id_user; ?></li>
		<li><?php echo $item->users->username; ?></li>
	</ul>
<?php endforeach ?>


<ul class="pagination" role="menubar" aria-label="Pagination">
	<?php if ($page->current != $page->first): ?>
		<li>
			<a href="<?php echo $this->url->get("/find-routes"); ?>">First</a>
		</li>
		<li class="arrow"><a
				href="<?php echo $this->url->get("/find-routes/" . $page->before);?>">&laquo;
				Previous</a></li>
	<?php endif ?>

	<li class="current"><a href=""><?php echo $page->current; ?></a></li>
	<li class="unavailable" aria-disabled="true"><a href="">&hellip;
			of <?php echo $page->total_items; ?></a></li>

	<?php if ($page->current != $page->last): ?>
		<li class="arrow"><a
				href="<?php echo $this->url->get("/find-routes/" . $page->next);?>">Next &raquo;</a>
		</li>
		<li>
			<a href="<?php echo $this->url->get("/find-routes/" . $page->last);?>">Last</a>
		</li>
	<?php endif ?>

</ul>

