<?php $this->flashSession->output(); ?>


	<?php if (isset($country_short_name)): ?>

		<ul class="breadcrumbs">
			<li><a href="<?php echo $this->url->get("/find-by-country"); ?>">Find By Country</a></li>
			<li><span class="flag-icon flag-icon-<?php echo strtolower($country_short_name); ?>"></span>&nbsp;<?php echo $country_long_name; ?></li>
		</ul>

	<?php endif ?>

<div style="margin-top: 2em;" class="row">

	<?php if (isset($allCountries)): ?>

		<div id="container" class="large-12 columns transitions-enabled large-centered clearfix">

			<?php foreach ($allCountries as $country): ?>
		        <div class="box col3">
		            <div class="thumbnail">
						<div class="flag-wrapper">
							<div class="img-thumbnail flag flag-icon-background flag-icon-<?php echo strtolower($country->country_short_name); ?>" title="<?php echo $country->country_short_name; ?>"></div>
						</div>
		                <div class="caption text-center BarnieFonte">
		                    <h3 style="font-size: 1.5em;" class=""><?php echo $country->country_long_name; ?></h3>
		                </div>
		            </div>
		        </div>

			<?php endforeach ?>

		</div>

	<?php else: ?>

		<span class="flag-icon flag-icon-<?php echo strtolower($country_short_name); ?>"></span>
		<?php echo $country_long_name; ?>

		<div class="row text-center panel">
			<div class="large-12 columns">
				<h2>Results:</h2>
				<ul class="small-block-grid-2">
					<li>
						<a href="<?php echo $this->url->get("/find-users-in-country/". $country_short_name);?>">
							<img class="th" src="http://placehold.it/250x250&amp;text=2312653 Users">
							<h4><?php echo isset($num_users) ? $num_users : "";?></h4>
						</a>

					</li>
					<li>
						<a href="<?php echo $this->url->get("/find-polaroids-in-country/" . $country_short_name); ?>">
							<img class="th" src="http://placehold.it/250x250&amp;text=23434 Polaroids">
							<h4><?php echo isset($num_polaroids) ? $num_polaroids : "";?></h4>
						</a>

					</li>
				</ul>
			</div>
		</div>

	<?php endif ?>

</div>
