<h1 class="headers-provisorios">FindController - countryAction</h1>

<?php $this->flashSession->output(); ?>

<?php if (isset($all_countries)): ?>

	<?php foreach ($all_countries as $country): ?>
		<span class="flag-icon flag-icon-<?php echo strtolower($country->country_short_name); ?>"></span>
	<?php endforeach ?>

<?php else: ?>

	<?php echo $country_long_name; ?>
	<?php echo $number_of_users_in_country; ?>
	<?php echo $number_of_polaroids_in_country; ?>

<?php endif ?>
