<h1 class="headers-provisorios">PolaroidController - createAction</h1>

<?php $this->flashSession->output(); ?>

<div class="row panel">
	<form action="<?php echo $this->url->get("/create-polaroid"); ?>" accept-charset="utf-8" method="post">

		<div class="row text-center">
			<div style="background-color: white;"
			     class="large-6 small-12 medium-6 text-center small-centered columns panel">

				<input type="hidden"
				       name="<?php echo $this->security->getTokenKey() ?>"
				       value="<?php echo $this->security->getToken() ?>">

				<img id="polaroid_to_edit"
				     src="public/img/polaroids/<?php echo $this->session->get("photo_name");?>">

				<input type='image' src='http://images.aviary.com/images/edit-photo.png'
				       value='Edit photo'
				       onclick="return launchEditor('polaroid_to_edit',
					       'http://polaroid-map-app.t.proxylocal.com/polaroid-map-app/public/img/polaroids/<?php echo $this->session->get("photo_name"); ?>');"/>

				<input id="polaroid_location"
				       name="polaroid_location"
				       type="hidden"
				       value="public/img/polaroids/<?php echo $this->session->get("photo_name");?>"/>

				<div class="panel">
					<input type="text"
					       id="polaroid_title"
					       name="polaroid_title"
					       class="text-center"
					       placeholder="insert the polaroid's title..."/>

					<hr/>
						<textarea style="resize: none;"
						          name="polaroid_description"
						          id="polaroid_description"
						          class="text-center"
						          placeholder="insert the polaroid's description..."
						          cols="30"
						          rows="5"></textarea>
				</div>
			</div>
		</div>
		<div class="row text-center">
			<input type="submit" class="button success"
			       value="Upload Polaroid"/>
		</div>
	</form>
</div>
