<h1 class="headers-provisorios">PolaroidController - showAction</h1>

<?php $this->flashSession->output(); ?>

<div class="row panel">
	<div class="row panel">
		<div class="small-6 columns text-left">
			<a href="<?php echo $this->url->get("/user/" .
				$polaroid_info->users->id . "/" .
				$polaroid_info->users->username); ?>">
				<img src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim($polaroid_info->users->email))); ?>?s=40"
					alt="<?php echo $polaroid_info->users->username; ?> photo.."/>
			</a>
			<a href="<?php echo $this->url->get("/user/" .
				$polaroid_info->users->id . "/" .
				$polaroid_info->users->username); ?>">
				<?php echo $polaroid_info->users->username; ?></a>
		</div>
		<div class="small-6 columns text-right">
			<span id="numberOfLikes"><?php echo $polaroid_info->number_of_likes;
				?></span> Likes
		</div>
	</div>
	<div class="row">
		<!-- large-6 small-12 medium-6 text-center small-centered columns
		panel -->
		<div style="background-color: white;"
		     class="large-6 columns panel text-center">
			<div class="panel">
				<img src="<?php echo $this->url->get("/public/img/polaroids/" . $polaroid_info->photo_hash_file_name); ?>"/>
			</div>

			<div class="panel">
				<h3><?php echo $polaroid_info->title; ?></h3>
				<h5 class="subheader"><?php echo $polaroid_info->description; ?></h5>
			</div>
		</div>
		<div style="background-color: white;"
		     class="large-6 columns panel">
			<div id="map-canvas"></div>
		</div>
	</div>
</div>

<?php if (!$this->session->has("auth")): ?>

	<div class="row text-center">
		<ul class="button-group even-1">
			<li>
				<a href="<?php echo $this->url->get("/sign-in-up?return_to="
					. $this->router->getRewriteUri());	?>"
				   class="button">
					<i style="font-size: 20px;"
					   class="fi-like"></i> Login to like and follow people!
				</a>
			</li>
		</ul>
	</div>

<?php endif ?>

<div class="row panel">
	<form action="<?php echo("/polaroid-map-app/like-polaroid"); ?>"
	      method="post">

		<input type="hidden"
		       name="<?php echo $this->security->getTokenKey(); ?>"
		       value="<?php echo $this->security->getToken(); ?>">

		<input type="hidden" name="polaroid_id"
		       value="<?php echo $polaroid_info->id;
		       ?>"/>

		<button type="submit" id="likePolaroidButton"
		        class="button expand">
			<i style="font-size: 20px;"
			   class="fi-like"></i> Like
		</button>
	</form>
</div>

<script>
	function initialize()
	{
		var myLatlng = new google.maps.LatLng(<?php echo $polaroid_info->lat;?>,
											  <?php echo $polaroid_info->lon;?>);

		var mapOptions = {
			zoom: 11,
			center: myLatlng,
			disableDefaultUI: true
		};

		var map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);

		var marker = new google.maps.Marker({
		position: myLatlng,
		map: map,
		title: "<?php echo $polaroid_info->title; ?>"
		});
	}
	google.maps.event.addDomListener(window, 'load', initialize);
</script>
