<?php $this->flashSession->output(); ?>

<div class="panel">
	<div class="row panel" style="background-color: white;">
		<div class="small-6 columns text-left">
			<a href="<?php echo $this->url->get("/user/" .
				$polaroid_info->users->id . "/" .
				$polaroid_info->users->username); ?>">
				<img src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim($polaroid_info->users->email))); ?>?s=40&d=<?php echo urlencode("http://polaroid-map-app.t.proxylocal.com/polaroid-map-app/img/misc/monster.png");?>"
					alt="<?php echo $polaroid_info->users->username; ?> photo.."/>
			</a>
			<a href="<?php echo $this->url->get("/user/" .
				$polaroid_info->users->id . "/" .
				$polaroid_info->users->username); ?>">
				<?php echo $polaroid_info->users->username; ?></a>
		</div>
		<div class="small-6 columns text-right">
			<span id="numberOfLikes"><?php echo $polaroid_info->number_of_likes;
				?></span> Likes
		</div>
	</div>
	<div class="row">
		<div id="primeiraDiv" style="background-color: white;"
		     class="large-6 large-uncentered medium-8 small-12 small-centered columns panel text-center">
			<div class="">
				<img src="<?php echo $this->url->get("/public/img/polaroids/" . $polaroid_info->photo_hash_file_name); ?>"/>
			</div>
			<a href="#" data-reveal-id="viewPolaroidModal"><i style="color: darkgrey; font-size: 2em;" class="fi-eye app-icons"></i></a>
			<a href="#" id="mapToggle"><i style="color: darkgrey; font-size: 1.4em; margin-right: 10px; margin-top: 0px;" class="right fi-map app-icons"></i></a>
			<div style="background-color: white; border: none;" class="panel">
				<h3 style="font-size: 2.3em; font-weight: bolder;"><?php echo $polaroid_info->title; ?></h3>
				<p style="  font-size: 1.6em;" class="subheader"><?php echo $polaroid_info->description; ?></p>
				<p class="right">
					<?php echo date("F j, Y", strtotime($polaroid_info->datetime_created)); ?>
					<a href="<?php echo $this->url->get("/find-by-country/". strtolower($polaroid_info->country)); ?>"><span class="flag-icon flag-icon-<?php echo strtolower($user_info->country); ?>"></span></a>
				</p>
			</div>
		</div>
		<div id="segundaDiv" style="background-color: white;"
		     class="large-6 large-uncentered medium-8 small-12 small-centered columns panel">
			<div id="map-canvinhas"></div>
		</div>
	</div>
</div>

<div id="viewPolaroidModal" class="reveal-modal" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog">
	<br>
	<div class="row panel text-center">
		<img src="<?php echo $this->url->get("/public/img/polaroids/" . $polaroid_info->photo_hash_file_name); ?>"/>
	</div>
  <a class="close-reveal-modal" aria-label="Close">&#215;</a>
</div>

<?php if (!$this->session->has("auth")): ?>

	<div class="row text-center">
				<a href="<?php echo $this->url->get("/sign-in-up?return_to="
					. $this->router->getRewriteUri());	?>"
				   class="button round expand warning">
					<i style="font-size: 20px;"
					   class="fi-upload-cloud"></i> Login to Like this Polaroid!
				</a>
	</div>

<?php else: ?>

	<?php if ($user_likes_polaroid_or_not): ?>

		<div class="row panel">
			<form action="<?php echo("/polaroid-map-app/unlike-polaroid"); ?>"
			      method="post">

				<input type="hidden"
				       name="<?php echo $this->security->getTokenKey(); ?>"
				       value="<?php echo $this->security->getToken(); ?>">

				<input type="hidden" name="polaroid_id"
				       value="<?php echo $polaroid_info->id;
				       ?>"/>

				<button type="submit" id="unlikePolaroidButton"
				        class="button expand info round">
					<i style="font-size: 20px;"
					   class="fi-dislike"></i> UnLike
				</button>
			</form>
		</div>

	<?php else: ?>
		<div class="row panel">
			<form action="<?php echo("/polaroid-map-app/like-polaroid"); ?>"
			      method="post">

				<input type="hidden"
				       name="<?php echo $this->security->getTokenKey(); ?>"
				       value="<?php echo $this->security->getToken(); ?>">

				<input type="hidden" name="polaroid_id"
				       value="<?php echo $polaroid_info->id;
				       ?>"/>

				<button type="submit" id="likePolaroidButton"
				        class="button expand round">
					<i style="font-size: 20px;"
					   class="fi-like"></i> Like
				</button>
			</form>
		</div>
	<?php endif ?>

<?php endif ?>


<script>
	function initialize()
	{
		var myLatlng = new google.maps.LatLng(<?php echo $polaroid_info->lat;?>,
											  <?php echo $polaroid_info->lon;?>);

		var mapOptions = {
			zoom: 11,
			center: myLatlng,
			disableDefaultUI: true
		};

		var map = new google.maps.Map(document.getElementById('map-canvinhas'), mapOptions);

		var marker = new google.maps.Marker({
			icon: {
                        url: "/polaroid-map-app/public/img/markers/red.png",
                        size: new google.maps.Size(30, 30),
                        origin: new google.maps.Point(0, 0),
                        anchor: new google.maps.Point(0, 30)
            },
			position: myLatlng,
			map: map,
			title: "<?php echo $polaroid_info->title; ?>"
		});


		$("#map-canvinhas").height( $("#primeiraDiv").height() + "px" );

	}
	google.maps.event.addDomListener(window, 'load', initialize);

</script>
