<?php $this->flashSession->output(); ?>

<div class="panel">
	<div class="row panel" style="background-color: white;">
		<div class="small-6 columns text-left">
			<a href="<?php echo $this->url->get("/user/" .
				$polaroid_info->users->id . "/" .
				$polaroid_info->users->username); ?>">
				<img src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim($polaroid_info->users->email))); ?>?s=40"
					alt="<?php echo $polaroid_info->users->username; ?> photo.."/>
			</a>
			<a href="<?php echo $this->url->get("/user/" .
				$polaroid_info->users->id . "/" .
				$polaroid_info->users->username); ?>">
				<?php echo $polaroid_info->users->username; ?></a>
		</div>
		<div class="small-6 columns text-right">
			<span id="numberOfLikes"><?php echo $polaroid_info->number_of_likes;
				?></span> Likes
		</div>
	</div>
	<div class="row">
		<div id="primeiraDiv" style="background-color: white;"
		     class="large-6 columns panel text-center">
			<div class="panel">
				<img src="<?php echo $this->url->get("/public/img/polaroids/" . $polaroid_info->photo_hash_file_name); ?>"/>
			</div>
			<a href="#" data-reveal-id="viewPolaroidModal"><i style="color: darkgrey; font-size: 2em;" class="fi-eye app-icons"></i></a>
			<div class="panel">
				<h3><?php echo $polaroid_info->title; ?></h3>
				<h5 class="subheader"><?php echo $polaroid_info->description; ?></h5>
			</div>
		</div>
		<div id="segundaDiv" style="background-color: white;"
		     class="large-6 columns panel">
			<div id="map-canvinhas"></div>
		</div>
	</div>
</div>

<div id="viewPolaroidModal" class="reveal-modal" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog">
	<br>
	<div class="row panel">
		<img src="<?php echo $this->url->get("/public/img/polaroids/" . $polaroid_info->photo_hash_file_name); ?>"/>
	</div>
  <a class="close-reveal-modal" aria-label="Close">&#215;</a>
</div>

<?php if (!$this->session->has("auth")): ?>

	<div class="row text-center">
				<a href="<?php echo $this->url->get("/sign-in-up?return_to="
					. $this->router->getRewriteUri());	?>"
				   class="button expand warning">
					<i style="font-size: 20px;"
					   class="fi-upload-cloud"></i> Login to like and follow people!
				</a>
	</div>

<?php else: ?>

<div class="row panel">
	<form action="<?php echo("/polaroid-map-app/like-polaroid"); ?>"
	      method="post">

		<input type="hidden"
		       name="<?php echo $this->security->getTokenKey(); ?>"
		       value="<?php echo $this->security->getToken(); ?>">

		<input type="hidden" name="polaroid_id"
		       value="<?php echo $polaroid_info->id;
		       ?>"/>

		<button type="submit" id="likePolaroidButton"
		        class="button expand">
			<i style="font-size: 20px;"
			   class="fi-like"></i> Like
		</button>
	</form>
</div>

<?php endif ?>


<script>
	function initialize()
	{
		var myLatlng = new google.maps.LatLng(<?php echo $polaroid_info->lat;?>,
											  <?php echo $polaroid_info->lon;?>);

		var mapOptions = {
			zoom: 11,
			center: myLatlng,
			disableDefaultUI: true
		};

		var map = new google.maps.Map(document.getElementById('map-canvinhas'), mapOptions);

		var marker = new google.maps.Marker({
		position: myLatlng,
		map: map,
		title: "<?php echo $polaroid_info->title; ?>"
		});


		$("#map-canvinhas").height( $("#primeiraDiv").height() + "px" );

	}
	google.maps.event.addDomListener(window, 'load', initialize);
</script>
