<?php $this->flashSession->output(); ?>

<div class="row panel" style="margin-top: 37px;">
	<div class="row">

		<ul class="tabs text-center" data-tab="" role="tablist"
		    data-options="deep_linking: true">
			<li style="float: none !important;
display: inline-block;" class="tab-title active" role="presentational">
				<a  href="#personal-info"
				    role="tab"
				    tabindex="0"
					aria-selected="true"
					controls="tabs-deeplink-1">Personal Info
				</a>
			</li>
			<li  style="float: none !important;
display: inline-block;" class="tab-title" role="presentational">
				<a  href="#settings"
					role="tab"
					tabindex="0"
					aria-selected="false"
					controls="tabs-deeplink-2">Account Settings
				</a>
			</li>
			<li  style="float: none !important;
display: inline-block;" class="tab-title" role="presentational">
				<a  href="#danger"
					role="tab"
					tabindex="0"
					aria-selected="false"
					controls="tabs-deeplink-3">Danger Zone
				</a>
			</li>
		</ul>

	</div>


	<div class="tabs-content">
			<section tabindex="0" id="personal-info" role="tabpanel"
			         aria-hidden="false" class="content active">

				<p id="tabs-deeplink-content-1">

				<div class="row text-center" style="margin-top: 17px; margin-bottom: 5px;">
					<img
					src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim($user_info->email))); ?>?s=100">
					<p>change your image at <a target="_blank" href="https://gravatar.com">gravatar.com</a> </p>
				</div>

				<form action="<?php echo $this->url->get("/personal-info"); ?>" method="post">
					<div class="row">
						<div class="small-12 columns">
							<span style="background-color: #444; color:
							white;" class="prefix">Name</span>
						</div>
						<div class="large-12 columns">
								<input type="text"
									   class="text-center"
									   name="full_name"
								       placeholder="Enter your Full Name..."
									   value="<?php echo $user_info->full_name;?>"/>
						</div>
					</div>
					<div class="row collapse text-center">
						<div class="small-12 columns">
							<span style="background-color: #46629E; color:
							white;"
							      class="prefix">facebook.com/</span>
						</div>
						<div class="small-12 columns">
				<input type="text" name="facebook" class="text-center" value="<?php echo $user_info->facebook_username; ?>" placeholder="Enter your facebook username...">
						</div>
					</div>
					<div class="row collapse text-center">
						<div class="small-12 columns">
							<span style="background-color: #55ACEE; color:
							white;" class="prefix">twitter.com/</span>
						</div>
						<div class="small-12 columns">
				<input type="text" name="twitter" class="text-center" value="<?php echo $user_info->twitter_username; ?>" placeholder="Enter your twitter username...">
						</div>
					</div>
					<div class="row collapse text-center">
						<div class="small-12 columns">
							<span style="background-color: #D73D32; color:
							white;" class="prefix">plus.google.com/</span>
						</div>
						<div class="small-12 columns">
				<input type="text" name="google_plus" class="text-center" value="<?php echo $user_info->google_plus_username; ?>" placeholder="Enter your google plus username...">
						</div>
					</div>

					<div class="row collapse text-center">
						<div class="small-12 columns">
							<span style="background-color: #444; color:
							white;" class="prefix">Bio</span>
						</div>
						<div class="small-12 columns">
								<textarea
									style="resize: none;"
									class="text-center"
									name="bio"
									rows="5"
									placeholder="Your Bio"><?php echo $user_info->bio; ?></textarea>
						</div>
					</div>

					<div class="row">
						<div class="small-12 columns">
							<span style="background-color: #444; color:
							white;" class="prefix">Country
								<span class="flag-icon flag-icon-<?php echo strtolower($user_info->country); ?>"></span>
							</span>

						</div>
						<div class="small-12 columns">
								<select
									class="text-center"
									name="country">
									<option value="">Country</option>
									<?php foreach (CountriesIcons::find() as $country): ?>
										<option value="<?php echo $country->country_short_name; ?>"
												<?php if ($user_info->country == $country->country_short_name): ?>
													selected
												<?php endif ?>
									 			>
									 			<?php echo $country->country_long_name; ?>
									    </option>
									<?php endforeach ?>
								</select>
							</label>
						</div>
					</div>

					<br/><br/>
						<input type="hidden"
				       name="<?php echo $this->security->getTokenKey() ?>"
				       value="<?php echo $this->security->getToken() ?>">

					<input class="button round expand success" type="submit"
					       value="Update Info"/>
				</form>
				</p>
			</section>
			<section tabindex="0" id="settings" role="tabpanel"
			         aria-hidden="true" class="content">

				<p id="tabs-deeplink-content-2">

				<form action="<?php echo $this->url->get("/account-settings"); ?>" method="post">
					<div class="row collapse">
						<div class="small-12 columns">
							<span style="background-color: #007095; color:
							white;" class="prefix">New Password:</span>
						</div>
						<div class="small-12 columns">
							<input class="text-center"
							       style="font-size: 2em;"
							       type="password"
							       name="new_password" value="" />
						</div>
					</div>

					<div class="row collapse">
						<div class="small-12 columns">
							<span style="background-color: #007095; color:
							white;" class="prefix">Confirm Password:</span>
						</div>
						<div class="small-12 columns">
							<input class="text-center"
							       style="font-size: 2em;"
							       type="password"
							       name="confirmed_new_password"
							       value="" />
						</div>
					</div>

					<br/>

					<div class="row collapse">
						<div class="small-12 columns">
							<span style="background-color: #E99703; color:
							white;" class="prefix">Current Password:</span>
						</div>
						<div class="small-12 columns">
							<input class="text-center"
							       style="font-size: 2em;"
							       type="password"
							       name="current_password"
							       value="" />
						</div>
					</div>

					<input type="hidden"
				       name="<?php echo $this->security->getTokenKey() ?>"
				       value="<?php echo $this->security->getToken() ?>">

		<br>

						<input class="button round expand success"
						       type="submit"
						       value="Submit new Password"/>

				</form>
				</p>
			</section>


			<section tabindex="0" id="danger" role="tabpanel"
						         aria-hidden="true" class="content">
				<p id="tabs-deeplink-content-3">
					<br/>
					<br/>
					<a class="button expand alert round" data-reveal-id="delete-account" href="#">Delete Account</a>
				</p>
			</section>

		</div>
</div>



<div id="delete-account"
     class="reveal-modal"
     data-reveal
     aria-labelledby="modalTitle"
     aria-hidden="true" role="dialog">
	<h2 id="modalTitle">Enter your current password to delete your account...</h2>

	<p class="lead">
		<form action="<?php echo $this->url->get("/danger-zone"); ?>" method="post">
			<div class="row collapse text-center">
				<div class="small-3 large-2 columns">
										<span style="background-color: #007095; color:
										white;"
										      class="prefix">Current Password:</span>
				</div>
				<div class="small-9 large-10 columns">
					<input type="password" name="current_password"
					       value="">
				</div>
				<input type="hidden"
				       name="<?php echo $this->security->getTokenKey() ?>"
				       value="<?php echo $this->security->getToken() ?>">
				<br/><br/><br/>
				<input type="submit" class="button warning"
				       value="Delete My Account"/>
			</div>
		</form>
	</p>
	<a class="close-reveal-modal" aria-label="Close">&#215;</a>
</div>
