<h1 class="headers-provisorios">UserController - accountAction</h1>

<div class="row panel">
	<div class="row panel">

		<ul class="tabs" data-tab="" role="tablist"
		    data-options="deep_linking: true">
			<li class="tab-title active" role="presentational">
				<a  href="#personal-info"
				    role="tab"
				    tabindex="0"
					aria-selected="true"
					controls="tabs-deeplink-1">Personal Info
				</a>
			</li>
			<li class="tab-title" role="presentational">
				<a  href="#settings"
					role="tab"
					tabindex="0"
					aria-selected="false"
					controls="tabs-deeplink-2">Account Settings
				</a>
			</li>
<!--			<li class="tab-title active" role="presentational"><a-->
<!--					href="#tabs-deeplink-3" role="tab" tabindex="-1"-->
<!--					aria-selected="true" controls="tabs-deeplink-3">Tab 3</a>-->
<!--			</li>-->
		</ul>

	</div>

	<div class="tabs-content">
			<section tabindex="0" id="personal-info" role="tabpanel"
			         aria-hidden="false" class="content active">
				<h3>Personal Info</h3>

				<p id="tabs-deeplink-content-1">

				<form action="" method="post">
					<div class="row">
						<div class="large-12 columns">
							<label>Full Name:
								<input type="text"
								       placeholder=""
										value="<?php echo "Ricardo Valério";
										?>"/>
							</label>
						</div>
					</div>
					<div class="row collapse">
						<div class="small-3 large-2 columns">
							<span style="background-color: #46629E; color:
							white;"
							      class="prefix">facebook.com/</span>
						</div>
						<div class="small-9 large-10 columns">
				<input type="text" placeholder="Enter your facebook username...">
						</div>
					</div>
					<div class="row collapse">
						<div class="small-3 large-2 columns">
							<span style="background-color: #55ACEE; color:
							white;" class="prefix">twitter.com/</span>
						</div>
						<div class="small-9 large-10 columns">
				<input type="text" placeholder="Enter your twitter username...">
						</div>
					</div>
					<div class="row collapse">
						<div class="small-3 large-2 columns">
							<span style="background-color: #D73D32; color:
							white;" class="prefix">plus.google.com/</span>
						</div>
						<div class="small-9 large-10 columns">
				<input type="text" placeholder="Enter your google plus username...">
						</div>
					</div>

					<div class="row">
						<div class="large-12 columns">
							<label>Country:
								<select
									class="ember-view ember-select form-control country-select"
									id="ember906">
									<option value="">Country</option>
									<option value="US" class="ember-view"
									        id="ember915">United States
									</option>
									<option value="AF" class="ember-view"
									        id="ember917">Afghanistan
									</option>
									<option value="AX" class="ember-view"
									        id="ember919">Åland Islands
									</option>
									<option value="AL" class="ember-view"
									        id="ember921">Albania
									</option>
									<option value="DZ" class="ember-view"
									        id="ember923">Algeria
									</option>
									<option value="AS" class="ember-view"
									        id="ember925">American Samoa
									</option>
									<option value="AD" class="ember-view"
									        id="ember927">Andorra
									</option>
									<option value="AO" class="ember-view"
									        id="ember929">Angola
									</option>
									<option value="AI" class="ember-view"
									        id="ember931">Anguilla
									</option>
									<option value="AQ" class="ember-view"
									        id="ember933">Antarctica
									</option>
									<option value="AG" class="ember-view"
									        id="ember935">Antigua and Barbuda
									</option>
									<option value="AR" class="ember-view"
									        id="ember937">Argentina
									</option>
									<option value="AM" class="ember-view"
									        id="ember939">Armenia
									</option>
									<option value="AW" class="ember-view"
									        id="ember941">Aruba
									</option>
									<option value="AU" class="ember-view"
									        id="ember943">Australia
									</option>
									<option value="AT" class="ember-view"
									        id="ember945">Austria
									</option>
									<option value="AZ" class="ember-view"
									        id="ember947">Azerbaijan
									</option>
									<option value="BS" class="ember-view"
									        id="ember949">Bahamas
									</option>
									<option value="BH" class="ember-view"
									        id="ember951">Bahrain
									</option>
									<option value="BD" class="ember-view"
									        id="ember953">Bangladesh
									</option>
									<option value="BB" class="ember-view"
									        id="ember955">Barbados
									</option>
									<option value="BY" class="ember-view"
									        id="ember957">Belarus
									</option>
									<option value="BE" class="ember-view"
									        id="ember959">Belgium
									</option>
									<option value="BZ" class="ember-view"
									        id="ember961">Belize
									</option>
									<option value="BJ" class="ember-view"
									        id="ember963">Benin
									</option>
									<option value="BM" class="ember-view"
									        id="ember965">Bermuda
									</option>
									<option value="BT" class="ember-view"
									        id="ember967">Bhutan
									</option>
									<option value="BO" class="ember-view"
									        id="ember969">Bolivia, Plurinational
									                      State of
									</option>
									<option value="BQ" class="ember-view"
									        id="ember971">Bonaire, Sint
									                      Eustatius and Saba
									</option>
									<option value="BA" class="ember-view"
									        id="ember973">Bosnia and Herzegovina
									</option>
									<option value="BW" class="ember-view"
									        id="ember975">Botswana
									</option>
									<option value="BV" class="ember-view"
									        id="ember977">Bouvet Island
									</option>
									<option value="BR" class="ember-view"
									        id="ember979">Brazil
									</option>
									<option value="IO" class="ember-view"
									        id="ember981">British Indian Ocean
									                      Territory
									</option>
									<option value="BN" class="ember-view"
									        id="ember983">Brunei Darussalam
									</option>
									<option value="BG" class="ember-view"
									        id="ember985">Bulgaria
									</option>
									<option value="BF" class="ember-view"
									        id="ember987">Burkina Faso
									</option>
									<option value="BI" class="ember-view"
									        id="ember989">Burundi
									</option>
									<option value="KH" class="ember-view"
									        id="ember991">Cambodia
									</option>
									<option value="CM" class="ember-view"
									        id="ember993">Cameroon
									</option>
									<option value="CA" class="ember-view"
									        id="ember995">Canada
									</option>
									<option value="CV" class="ember-view"
									        id="ember997">Cabo Verde
									</option>
									<option value="KY" class="ember-view"
									        id="ember999">Cayman Islands
									</option>
									<option value="CF" class="ember-view"
									        id="ember1001">Central African
									                       Republic
									</option>
									<option value="TD" class="ember-view"
									        id="ember1003">Chad
									</option>
									<option value="CL" class="ember-view"
									        id="ember1005">Chile
									</option>
									<option value="CN" class="ember-view"
									        id="ember1007">China
									</option>
									<option value="CX" class="ember-view"
									        id="ember1009">Christmas Island
									</option>
									<option value="CC" class="ember-view"
									        id="ember1011">Cocos (Keeling)
									                       Islands
									</option>
									<option value="CO" class="ember-view"
									        id="ember1013">Colombia
									</option>
									<option value="KM" class="ember-view"
									        id="ember1015">Comoros
									</option>
									<option value="CG" class="ember-view"
									        id="ember1017">Congo
									</option>
									<option value="CD" class="ember-view"
									        id="ember1019">Congo, the Democratic
									                       Republic of the
									</option>
									<option value="CK" class="ember-view"
									        id="ember1021">Cook Islands
									</option>
									<option value="CR" class="ember-view"
									        id="ember1023">Costa Rica
									</option>
									<option value="CI" class="ember-view"
									        id="ember1025">Côte d'Ivoire
									</option>
									<option value="HR" class="ember-view"
									        id="ember1027">Croatia
									</option>
									<option value="CU" class="ember-view"
									        id="ember1029">Cuba
									</option>
									<option value="CW" class="ember-view"
									        id="ember1031">Curaçao
									</option>
									<option value="CY" class="ember-view"
									        id="ember1033">Cyprus
									</option>
									<option value="CZ" class="ember-view"
									        id="ember1035">Czech Republic
									</option>
									<option value="DK" class="ember-view"
									        id="ember1037">Denmark
									</option>
									<option value="DJ" class="ember-view"
									        id="ember1039">Djibouti
									</option>
									<option value="DM" class="ember-view"
									        id="ember1041">Dominica
									</option>
									<option value="DO" class="ember-view"
									        id="ember1043">Dominican Republic
									</option>
									<option value="EC" class="ember-view"
									        id="ember1045">Ecuador
									</option>
									<option value="EG" class="ember-view"
									        id="ember1047">Egypt
									</option>
									<option value="SV" class="ember-view"
									        id="ember1049">El Salvador
									</option>
									<option value="GQ" class="ember-view"
									        id="ember1051">Equatorial Guinea
									</option>
									<option value="ER" class="ember-view"
									        id="ember1053">Eritrea
									</option>
									<option value="EE" class="ember-view"
									        id="ember1055">Estonia
									</option>
									<option value="ET" class="ember-view"
									        id="ember1057">Ethiopia
									</option>
									<option value="FK" class="ember-view"
									        id="ember1059">Falkland Islands
									                       (Malvinas)
									</option>
									<option value="FO" class="ember-view"
									        id="ember1061">Faroe Islands
									</option>
									<option value="FJ" class="ember-view"
									        id="ember1063">Fiji
									</option>
									<option value="FI" class="ember-view"
									        id="ember1065">Finland
									</option>
									<option value="FR" class="ember-view"
									        id="ember1067">France
									</option>
									<option value="GF" class="ember-view"
									        id="ember1069">French Guiana
									</option>
									<option value="PF" class="ember-view"
									        id="ember1071">French Polynesia
									</option>
									<option value="TF" class="ember-view"
									        id="ember1073">French Southern
									                       Territories
									</option>
									<option value="GA" class="ember-view"
									        id="ember1075">Gabon
									</option>
									<option value="GM" class="ember-view"
									        id="ember1077">Gambia
									</option>
									<option value="GE" class="ember-view"
									        id="ember1079">Georgia
									</option>
									<option value="DE" class="ember-view"
									        id="ember1081">Germany
									</option>
									<option value="GH" class="ember-view"
									        id="ember1083">Ghana
									</option>
									<option value="GI" class="ember-view"
									        id="ember1085">Gibraltar
									</option>
									<option value="GR" class="ember-view"
									        id="ember1087">Greece
									</option>
									<option value="GL" class="ember-view"
									        id="ember1089">Greenland
									</option>
									<option value="GD" class="ember-view"
									        id="ember1091">Grenada
									</option>
									<option value="GP" class="ember-view"
									        id="ember1093">Guadeloupe
									</option>
									<option value="GU" class="ember-view"
									        id="ember1095">Guam
									</option>
									<option value="GT" class="ember-view"
									        id="ember1097">Guatemala
									</option>
									<option value="GG" class="ember-view"
									        id="ember1099">Guernsey
									</option>
									<option value="GN" class="ember-view"
									        id="ember1101">Guinea
									</option>
									<option value="GW" class="ember-view"
									        id="ember1103">Guinea-Bissau
									</option>
									<option value="GY" class="ember-view"
									        id="ember1105">Guyana
									</option>
									<option value="HT" class="ember-view"
									        id="ember1107">Haiti
									</option>
									<option value="HM" class="ember-view"
									        id="ember1109">Heard Island and
									                       McDonald Islands
									</option>
									<option value="VA" class="ember-view"
									        id="ember1111">Holy See (Vatican
									                       City State)
									</option>
									<option value="HN" class="ember-view"
									        id="ember1113">Honduras
									</option>
									<option value="HK" class="ember-view"
									        id="ember1115">Hong Kong
									</option>
									<option value="HU" class="ember-view"
									        id="ember1117">Hungary
									</option>
									<option value="IS" class="ember-view"
									        id="ember1119">Iceland
									</option>
									<option value="IN" class="ember-view"
									        id="ember1121">India
									</option>
									<option value="ID" class="ember-view"
									        id="ember1123">Indonesia
									</option>
									<option value="IR" class="ember-view"
									        id="ember1125">Iran, Islamic
									                       Republic of
									</option>
									<option value="IQ" class="ember-view"
									        id="ember1127">Iraq
									</option>
									<option value="IE" class="ember-view"
									        id="ember1129">Ireland
									</option>
									<option value="IM" class="ember-view"
									        id="ember1131">Isle of Man
									</option>
									<option value="IL" class="ember-view"
									        id="ember1133">Israel
									</option>
									<option value="IT" class="ember-view"
									        id="ember1135">Italy
									</option>
									<option value="JM" class="ember-view"
									        id="ember1137">Jamaica
									</option>
									<option value="JP" class="ember-view"
									        id="ember1139">Japan
									</option>
									<option value="JE" class="ember-view"
									        id="ember1141">Jersey
									</option>
									<option value="JO" class="ember-view"
									        id="ember1143">Jordan
									</option>
									<option value="KZ" class="ember-view"
									        id="ember1145">Kazakhstan
									</option>
									<option value="KE" class="ember-view"
									        id="ember1147">Kenya
									</option>
									<option value="KI" class="ember-view"
									        id="ember1149">Kiribati
									</option>
									<option value="KP" class="ember-view"
									        id="ember1151">Korea, Democratic
									                       People's Republic of
									</option>
									<option value="KR" class="ember-view"
									        id="ember1153">Korea, Republic of
									</option>
									<option value="KW" class="ember-view"
									        id="ember1155">Kuwait
									</option>
									<option value="KG" class="ember-view"
									        id="ember1157">Kyrgyzstan
									</option>
									<option value="LA" class="ember-view"
									        id="ember1159">Lao People's
									                       Democratic Republic
									</option>
									<option value="LV" class="ember-view"
									        id="ember1161">Latvia
									</option>
									<option value="LB" class="ember-view"
									        id="ember1163">Lebanon
									</option>
									<option value="LS" class="ember-view"
									        id="ember1165">Lesotho
									</option>
									<option value="LR" class="ember-view"
									        id="ember1167">Liberia
									</option>
									<option value="LY" class="ember-view"
									        id="ember1169">Libya
									</option>
									<option value="LI" class="ember-view"
									        id="ember1171">Liechtenstein
									</option>
									<option value="LT" class="ember-view"
									        id="ember1173">Lithuania
									</option>
									<option value="LU" class="ember-view"
									        id="ember1175">Luxembourg
									</option>
									<option value="MO" class="ember-view"
									        id="ember1177">Macao
									</option>
									<option value="MK" class="ember-view"
									        id="ember1179">Macedonia, the former
									                       Yugoslav Republic of
									</option>
									<option value="MG" class="ember-view"
									        id="ember1181">Madagascar
									</option>
									<option value="MW" class="ember-view"
									        id="ember1183">Malawi
									</option>
									<option value="MY" class="ember-view"
									        id="ember1185">Malaysia
									</option>
									<option value="MV" class="ember-view"
									        id="ember1187">Maldives
									</option>
									<option value="ML" class="ember-view"
									        id="ember1189">Mali
									</option>
									<option value="MT" class="ember-view"
									        id="ember1191">Malta
									</option>
									<option value="MH" class="ember-view"
									        id="ember1193">Marshall Islands
									</option>
									<option value="MQ" class="ember-view"
									        id="ember1195">Martinique
									</option>
									<option value="MR" class="ember-view"
									        id="ember1197">Mauritania
									</option>
									<option value="MU" class="ember-view"
									        id="ember1199">Mauritius
									</option>
									<option value="YT" class="ember-view"
									        id="ember1201">Mayotte
									</option>
									<option value="MX" class="ember-view"
									        id="ember1203">Mexico
									</option>
									<option value="FM" class="ember-view"
									        id="ember1205">Micronesia, Federated
									                       States of
									</option>
									<option value="MD" class="ember-view"
									        id="ember1207">Moldova, Republic of
									</option>
									<option value="MC" class="ember-view"
									        id="ember1209">Monaco
									</option>
									<option value="MN" class="ember-view"
									        id="ember1211">Mongolia
									</option>
									<option value="ME" class="ember-view"
									        id="ember1213">Montenegro
									</option>
									<option value="MS" class="ember-view"
									        id="ember1215">Montserrat
									</option>
									<option value="MA" class="ember-view"
									        id="ember1217">Morocco
									</option>
									<option value="MZ" class="ember-view"
									        id="ember1219">Mozambique
									</option>
									<option value="MM" class="ember-view"
									        id="ember1221">Myanmar
									</option>
									<option value="NA" class="ember-view"
									        id="ember1223">Namibia
									</option>
									<option value="NR" class="ember-view"
									        id="ember1225">Nauru
									</option>
									<option value="NP" class="ember-view"
									        id="ember1227">Nepal
									</option>
									<option value="NL" class="ember-view"
									        id="ember1229">Netherlands
									</option>
									<option value="NC" class="ember-view"
									        id="ember1231">New Caledonia
									</option>
									<option value="NZ" class="ember-view"
									        id="ember1233">New Zealand
									</option>
									<option value="NI" class="ember-view"
									        id="ember1235">Nicaragua
									</option>
									<option value="NE" class="ember-view"
									        id="ember1237">Niger
									</option>
									<option value="NG" class="ember-view"
									        id="ember1239">Nigeria
									</option>
									<option value="NU" class="ember-view"
									        id="ember1241">Niue
									</option>
									<option value="NF" class="ember-view"
									        id="ember1243">Norfolk Island
									</option>
									<option value="MP" class="ember-view"
									        id="ember1245">Northern Mariana
									                       Islands
									</option>
									<option value="NO" class="ember-view"
									        id="ember1247">Norway
									</option>
									<option value="OM" class="ember-view"
									        id="ember1249">Oman
									</option>
									<option value="PK" class="ember-view"
									        id="ember1251">Pakistan
									</option>
									<option value="PW" class="ember-view"
									        id="ember1253">Palau
									</option>
									<option value="PS" class="ember-view"
									        id="ember1255">Palestine, State of
									</option>
									<option value="PA" class="ember-view"
									        id="ember1257">Panama
									</option>
									<option value="PG" class="ember-view"
									        id="ember1259">Papua New Guinea
									</option>
									<option value="PY" class="ember-view"
									        id="ember1261">Paraguay
									</option>
									<option value="PE" class="ember-view"
									        id="ember1263">Peru
									</option>
									<option value="PH" class="ember-view"
									        id="ember1265">Philippines
									</option>
									<option value="PN" class="ember-view"
									        id="ember1267">Pitcairn
									</option>
									<option value="PL" class="ember-view"
									        id="ember1269">Poland
									</option>
									<option value="PT" class="ember-view"
									        id="ember1271">Portugal
									</option>
									<option value="PR" class="ember-view"
									        id="ember1273">Puerto Rico
									</option>
									<option value="QA" class="ember-view"
									        id="ember1275">Qatar
									</option>
									<option value="RE" class="ember-view"
									        id="ember1277">Réunion
									</option>
									<option value="RO" class="ember-view"
									        id="ember1279">Romania
									</option>
									<option value="RU" class="ember-view"
									        id="ember1281">Russian Federation
									</option>
									<option value="RW" class="ember-view"
									        id="ember1283">Rwanda
									</option>
									<option value="BL" class="ember-view"
									        id="ember1285">Saint Barthélemy
									</option>
									<option value="SH" class="ember-view"
									        id="ember1287">Saint Helena,
									                       Ascension and Tristan
									                       da Cunha
									</option>
									<option value="KN" class="ember-view"
									        id="ember1289">Saint Kitts and Nevis
									</option>
									<option value="LC" class="ember-view"
									        id="ember1291">Saint Lucia
									</option>
									<option value="MF" class="ember-view"
									        id="ember1293">Saint Martin (French
									                       part)
									</option>
									<option value="PM" class="ember-view"
									        id="ember1295">Saint Pierre and
									                       Miquelon
									</option>
									<option value="VC" class="ember-view"
									        id="ember1297">Saint Vincent and the
									                       Grenadines
									</option>
									<option value="WS" class="ember-view"
									        id="ember1299">Samoa
									</option>
									<option value="SM" class="ember-view"
									        id="ember1301">San Marino
									</option>
									<option value="ST" class="ember-view"
									        id="ember1303">Sao Tome and Principe
									</option>
									<option value="SA" class="ember-view"
									        id="ember1305">Saudi Arabia
									</option>
									<option value="SN" class="ember-view"
									        id="ember1307">Senegal
									</option>
									<option value="RS" class="ember-view"
									        id="ember1309">Serbia
									</option>
									<option value="SC" class="ember-view"
									        id="ember1311">Seychelles
									</option>
									<option value="SL" class="ember-view"
									        id="ember1313">Sierra Leone
									</option>
									<option value="SG" class="ember-view"
									        id="ember1315">Singapore
									</option>
									<option value="SX" class="ember-view"
									        id="ember1317">Sint Maarten (Dutch
									                       part)
									</option>
									<option value="SK" class="ember-view"
									        id="ember1319">Slovakia
									</option>
									<option value="SI" class="ember-view"
									        id="ember1321">Slovenia
									</option>
									<option value="SB" class="ember-view"
									        id="ember1323">Solomon Islands
									</option>
									<option value="SO" class="ember-view"
									        id="ember1325">Somalia
									</option>
									<option value="ZA" class="ember-view"
									        id="ember1327">South Africa
									</option>
									<option value="GS" class="ember-view"
									        id="ember1329">South Georgia and the
									                       South Sandwich
									                       Islands
									</option>
									<option value="SS" class="ember-view"
									        id="ember1331">South Sudan
									</option>
									<option value="ES" class="ember-view"
									        id="ember1333">Spain
									</option>
									<option value="LK" class="ember-view"
									        id="ember1335">Sri Lanka
									</option>
									<option value="SD" class="ember-view"
									        id="ember1337">Sudan
									</option>
									<option value="SR" class="ember-view"
									        id="ember1339">Suriname
									</option>
									<option value="SJ" class="ember-view"
									        id="ember1341">Svalbard and Jan
									                       Mayen
									</option>
									<option value="SZ" class="ember-view"
									        id="ember1343">Swaziland
									</option>
									<option value="SE" class="ember-view"
									        id="ember1345">Sweden
									</option>
									<option value="CH" class="ember-view"
									        id="ember1347">Switzerland
									</option>
									<option value="SY" class="ember-view"
									        id="ember1349">Syrian Arab Republic
									</option>
									<option value="TW" class="ember-view"
									        id="ember1351">Taiwan
									</option>
									<option value="TJ" class="ember-view"
									        id="ember1353">Tajikistan
									</option>
									<option value="TZ" class="ember-view"
									        id="ember1355">Tanzania, United
									                       Republic of
									</option>
									<option value="TH" class="ember-view"
									        id="ember1357">Thailand
									</option>
									<option value="TL" class="ember-view"
									        id="ember1359">Timor-Leste
									</option>
									<option value="TG" class="ember-view"
									        id="ember1361">Togo
									</option>
									<option value="TK" class="ember-view"
									        id="ember1363">Tokelau
									</option>
									<option value="TO" class="ember-view"
									        id="ember1365">Tonga
									</option>
									<option value="TT" class="ember-view"
									        id="ember1367">Trinidad and Tobago
									</option>
									<option value="TN" class="ember-view"
									        id="ember1369">Tunisia
									</option>
									<option value="TR" class="ember-view"
									        id="ember1371">Turkey
									</option>
									<option value="TM" class="ember-view"
									        id="ember1373">Turkmenistan
									</option>
									<option value="TC" class="ember-view"
									        id="ember1375">Turks and Caicos
									                       Islands
									</option>
									<option value="TV" class="ember-view"
									        id="ember1377">Tuvalu
									</option>
									<option value="UG" class="ember-view"
									        id="ember1379">Uganda
									</option>
									<option value="UA" class="ember-view"
									        id="ember1381">Ukraine
									</option>
									<option value="AE" class="ember-view"
									        id="ember1383">United Arab Emirates
									</option>
									<option value="GB" class="ember-view"
									        id="ember1385">United Kingdom
									</option>
									<option value="UM" class="ember-view"
									        id="ember1387">United States Minor
									                       Outlying Islands
									</option>
									<option value="UY" class="ember-view"
									        id="ember1389">Uruguay
									</option>
									<option value="UZ" class="ember-view"
									        id="ember1391">Uzbekistan
									</option>
									<option value="VU" class="ember-view"
									        id="ember1393">Vanuatu
									</option>
									<option value="VE" class="ember-view"
									        id="ember1395">Venezuela, Bolivarian
									                       Republic of
									</option>
									<option value="VN" class="ember-view"
									        id="ember1397">Viet Nam
									</option>
									<option value="VG" class="ember-view"
									        id="ember1399">Virgin Islands,
									                       British
									</option>
									<option value="VI" class="ember-view"
									        id="ember1401">Virgin Islands, U.S.
									</option>
									<option value="WF" class="ember-view"
									        id="ember1403">Wallis and Futuna
									</option>
									<option value="EH" class="ember-view"
									        id="ember1405">Western Sahara
									</option>
									<option value="YE" class="ember-view"
									        id="ember1407">Yemen
									</option>
									<option value="ZM" class="ember-view"
									        id="ember1409">Zambia
									</option>
									<option value="ZW" class="ember-view"
									        id="ember1411">Zimbabwe
									</option>
								</select>
<!--								<select>-->
<!--									<option value="portugal">Portugal</option>-->
<!--									<option selected value="usa">USA</option>-->
<!--									<option value="brazil">Brazil</option>-->
<!--									<option value="france">France</option>-->
<!--								</select>-->
							</label>
						</div>
					</div>

					<br/><br/>

					<input class="button expand success" type="submit"
					       value="Update Info"/>
				</form>
				</p>
			</section>
			<section tabindex="0" id="settings" role="tabpanel"
			         aria-hidden="true" class="content">
				<h3>Account Settings</h3>

				<p id="tabs-deeplink-content-2">

				<form action="" method="post">
						<div class="row collapse">
						<div class="small-3 large-2 columns">
							<span style="background-color: #007095; color:
							white;" class="prefix">New Password:</span>
						</div>
						<div class="small-9 large-10 columns">
							<input type="password" name="password" value="">
						</div>
					</div>

					<div class="row collapse">
						<div class="small-3 large-2 columns">
							<span style="background-color: #007095; color:
							white;" class="prefix">Confirm Password:</span>
						</div>
						<div class="small-9 large-10 columns">
							<input type="password" name="confirmed_password"
							       value="">
						</div>
					</div>

					<br/><br/>
				<input class="button expand success" type="submit"
				       value="Update Password"/>

				</form>

				<br/>
				<br/>

				<h3>Danger Zone:</h3>
				<a class="button expand alert" data-reveal-id="delete-account"
				   href="#">Delete Account</a>

				</p>
			</section>
		</div>
</div>


<div id="delete-account"
     class="reveal-modal"
     data-reveal
     aria-labelledby="modalTitle"
     aria-hidden="true" role="dialog">
	<h2 id="modalTitle">Enter your current password to delete your account...</h2>

	<p class="lead">
		<form action="/user/delete-account" method="post">
			<div class="row collapse text-center">
				<div class="small-3 large-2 columns">
										<span style="background-color: #007095; color:
										white;"
										      class="prefix">Current Password:</span>
				</div>
				<div class="small-9 large-10 columns">
					<input type="password" name="password_to_delete"
					       value="">
				</div>
				<br/><br/><br/>
				<input type="submit" class="button warning"
				       value="Delete My Account"/>
			</div>
		</form>
	</p>
	<a class="close-reveal-modal" aria-label="Close">&#215;</a>
</div>


