<div class="row">

	<?php $counter = 0; ?>
	<?php foreach ($following as $f): ?>
		<div class="large-3 medium-6 small-12 columns panel">
			<div class="panel text-center">
				<img src="http://www.gravatar.com/avatar/<?php
				echo md5(strtolower(trim($f->users->email))); ?>?s=150">
			</div>
			<div class="panel text-center">
				<h4><?php echo $f->users->username; ?></h4>
				<a href="" class="button expand warning"><i class="fi-dislike"></i>
					Unfollow</a>
			</div>
		</div>

		<?php if ($counter++ == 3): ?>
			<?php echo "</div><div class='row'></div>";?>
		<?php endif ?>

	<?php endforeach ?>

</div>
