
<div style="margin-top: 2em;" class="row">
    <div id="container" class="large-12 columns transitions-enabled large-centered clearfix">

    <?php foreach ($following as $f): ?>
        <div class="box col3">
            <div class="thumbnail">
                <a href="<?php echo $this->url->get("/user/" . $f->users->id . "/" .
            $this->tag->friendlyTitle($f->users->username, "-")); ?>">
                <img src="http://www.gravatar.com/avatar/<?php
                echo md5(strtolower(trim($f->users->email))); ?>?s=150">
                </a>
                <div class="caption text-center BarnieFonte">
                    <h3 style="font-size: 1.5em;" class=""><?php echo $f->users->username; ?></h3>
                    <a href="" class="button alert expand round">Unfollow</a>
                </div>
            </div>
        </div>
    <?php endforeach ?>

    </div>
</div>
