<h1 class="headers-provisorios">UserController - followingAction</h1>

<div class="row">
	<div class="large-3 medium-6 small-12 columns">
		<img src="http://placehold.it/1000x1000&amp;text=Thumbnail">

		<div class="panel text-center">
			<a href="" class="button expand warning"><i class="fi-dislike"></i>
				Unfollow</a>
		</div>
	</div>
	<div class="large-3 medium-6 small-12 columns">
		<img src="http://placehold.it/1000x1000&amp;text=Thumbnail">

		<div class="panel text-center">
			<a href="" class="button expand warning"><i class="fi-dislike"></i>
				Unfollow</a>
		</div>
	</div>
	<div class="large-3 medium-6 small-12 columns">
		<img src="http://placehold.it/1000x1000&amp;text=Thumbnail">

		<div class="panel text-center">
			<a href="" class="button expand warning"><i class="fi-dislike"></i>
				Unfollow</a>
		</div>
	</div>
	<div class="large-3 medium-6 small-12 columns">
		<img src="http://placehold.it/1000x1000&amp;text=Thumbnail">

		<div class="panel text-center">
			<a href="" class="button expand warning"><i class="fi-dislike"></i>
				Unfollow</a>
		</div>
	</div>
</div>
