<div style="margin-top: 37px;" class="row text-center">
	<div class="medium-6 columns panel">
		<a href="#" data-reveal-id="LikePolaroidsModal">
			<img class="th"
		     src="http://placehold.it/250x250&amp;text=Polaroids">
		</a>
	</div>
	<div class="medium-6 columns panel">
		<a href="#" data-reveal-id="LikeRoutesModal">
			<img class="th"
			     src="http://placehold.it/250x250&amp;text=Routes">
		</a>
	</div>
</div>


<div id="LikePolaroidsModal" class="reveal-modal text-center" data-reveal
     aria-labelledby="modalTitle"
     aria-hidden="true" role="dialog">
	<h2 id="modalTitle">Polaroids Liked By USERNAME HERE</h2>

	<p class="lead">

	</p>
	<a class="close-reveal-modal" aria-label="Close">&#215;</a>
</div>


<div id="LikeRoutesModal" class="reveal-modal text-center" data-reveal
     aria-labelledby="modalTitle"
     aria-hidden="true" role="dialog">
	<h2 id="modalTitle">Routes Liked By USERNAME HERE</h2>

	<p class="lead">

	</p>
	<a class="close-reveal-modal" aria-label="Close">&#215;</a>
</div>
