<h1 class="headers-provisorios">UserController - placesAction</h1>


<div class="row">
	<div class="large-3 small-6 columns panel">
		<img src="http://placehold.it/500x500&amp;text=Thumbnail">

		<div class="panel">
			<p>Description</p>
		</div>
	</div>
	<div class="large-3 small-6 columns panel">
		<img src="http://placehold.it/500x500&amp;text=Thumbnail">

		<div class="panel">
			<p>Description</p>
		</div>
	</div>
	<div class="large-3 small-6 columns panel">
		<img src="http://placehold.it/500x500&amp;text=Thumbnail">

		<div class="panel">
			<p>Description</p>
		</div>
	</div>
	<div class="large-3 small-6 columns panel">
		<img src="http://placehold.it/500x500&amp;text=Thumbnail">

		<div class="panel">
			<p>Description</p>
		</div>
	</div>
</div>


<div class="row">
	<div class="large-3 small-6 columns panel">
		<img src="http://placehold.it/500x500&amp;text=Thumbnail">

		<div class="panel">
			<p>Description</p>
		</div>
	</div>
	<div class="large-3 small-6 columns panel">
		<img src="http://placehold.it/500x500&amp;text=Thumbnail">

		<div class="panel">
			<p>Description</p>
		</div>
	</div>
	<div class="large-3 small-6 columns panel">
		<img src="http://placehold.it/500x500&amp;text=Thumbnail">

		<div class="panel">
			<p>Description</p>
		</div>
	</div>
	<div class="large-3 small-6 columns panel">
		<img src="http://placehold.it/500x500&amp;text=Thumbnail">

		<div class="panel">
			<p>Description</p>
		</div>
	</div>
</div>
