<div class="row text-center">

	<?php $counter = 0; ?>
	<?php foreach ($user_polaroids as $user_polaroid): ?>

		<a href="<?php echo $this->url->get("/polaroid/" .
			$user_polaroid->id . "/" .
			$this->tag->friendlyTitle($user_polaroid->title, "-")); ?>">
			<div class="large-3 small-12 medium-3 columns panel">
				<img
					src="public/img/polaroids/<?php echo $user_polaroid->photo_hash_file_name; ?>">

				<div class="panel">
					<p><?php echo $user_polaroid->title; ?> </p>
				</div>
			</div>
		</a>

		<?php if ($counter++ == 3): ?>
			<?php echo "</div><div class='row text-center'>";?>
			<?php $counter = 0; ?>
		<?php endif ?>

	<?php endforeach ?>
