<?php $this->flashSession->output(); ?>

<div style="margin-top: 37px;" class="row">
	<div class="large-4 columns text-center panel">
		<div class="row text-center">
			<div class="large-6 text-left small-6 columns">
				<h4><?php echo $user_info->username; ?> </h4>
			</div>
			<div class="large-6 small-6 text-right columns">
				<span class="flag-icon flag-icon-<?php echo strtolower($user_info->country); ?>"></span>
			</div>
		</div>
		<img src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim($user_info->email))); ?>?s=250">
	</div>
	<div class="large-8 columns">
		<div class="panel radius">
			<div class="row">
				<div class="large-12 columns text-center">
					<?php if ($user_info->full_name): ?>
						<h4><?php echo $user_info->full_name; ?></h4>
						<hr>
					<?php endif ?>
				<h5 class="subheader">
					<div class="row collapse">
						<?php if ($user_info->facebook_username): ?>
							<div class="small-12 medium-4 end columns">
								<a href="https://facebook.com/<?php echo $user_info->facebook_username; ?>">
								<img src="/polaroid-map-app/public/img/social-icons/facebook.png" alt="<?php echo $user_info->facebook_username; ?>"> Facebook
								</a>
							</div>
						<?php endif ?>
						<?php if ($user_info->twitter_username): ?>

						<div class="small-12 medium-4 end columns">
							<a href="https://twitter.com/<?php echo $user_info->twitter_username; ?>">
							<img src="/polaroid-map-app/public/img/social-icons/twitter.png" alt="<?php echo $user_info->twitter_username; ?>"> Twitter
							</a>
						</div>
						<?php endif ?>
						<?php if ($user_info->google_plus_username): ?>
						<div class="small-12 medium-4 end columns">
							<a href="https://plus.google.com/<?php echo $user_info->google_plus_username; ?>">
								<img src="/polaroid-map-app/public/img/social-icons/googleplus.png" alt="<?php echo $user_info->google_plus_username; ?>"> Google +
							</a>
						</div>
						<?php endif ?>
					</div>
				</h5>
				</div>
			</div>
		</div>
		<?php if ($user_info->bio): ?>
		<div class="panel radius">
			<div class="row">
				<div class="large-12 columns">
					<?php echo $user_info->bio; ?>
				</div>
			</div>
		</div>
		<?php endif ?>
	</div>
</div>


<div class="row panel">
	<ul class="button-group even-2">
		<li>
			<a data-reveal-id="show-user-polaroids" href="#" class="button">
				<i style="font-size: 20px;"
				   class="fi-camera"></i> Polaroids
			</a>
		</li>
		<li>
			<a data-reveal-id="show-user-routes" href="#" class="button">
				<i style="font-size: 20px;"
				   class="fi-address-book"></i> Routes
			</a>
		</li>
	</ul>
</div>

<!-- modal para as polaroids-->
<div id="show-user-polaroids" class="reveal-modal" data-reveal
     aria-labelledby="Polaroids" aria-hidden="true" role="dialog">
	<h2 class="text-center" id="Polaroids"><?php echo $user_info->username;?>'s Polaroids!</h2>

	<div style="margin-top: 2em;" class="row">
	    <div id="container" class="large-12 columns transitions-enabled large-centered clearfix">

	    <?php foreach ($user_polaroids as $user_polaroid): ?>
	        <div class="box col3">
	            <div class="thumbnail">
	                <a href="<?php echo $this->url->get("/polaroid/" . $user_polaroid->id . "/" .
	            $this->tag->friendlyTitle($user_polaroid->title, "-")); ?>">
	                <img class="img-rounded BarnieFonte" src="/polaroid-map-app/public/img/polaroids/<?php echo $user_polaroid->photo_hash_file_name; ?>">
	                </a>
	                <div class="caption text-center BarnieFonte">
	                    <h3 style="font-size: 1.5em;" class="BarnieFonte"><?php echo $user_polaroid->title; ?></h3>
	                    <p style="margin-bottom: -0.75rem; border-top: 0.1px solid rgba(128, 128, 128, 0.2); padding-top: 5px;"><?php echo date("F j, Y", strtotime($user_polaroid->datetime_created)); ?></p> </div>
	            </div>
	        </div>
	    <?php endforeach ?>

	    </div>
	</div>
</div>


<!-- modal para as routes -->
<div id="show-user-routes" class="reveal-modal" data-reveal
     aria-labelledby="Routes" aria-hidden="true" role="dialog">
	<h2 class="text-center" id="Routes"><?php echo $user_info->username; ?>'s Routes</h2>

	<?php foreach ($user_routes as $user_route): ?>

		<div class="panel">
			<h4><?php echo $user_route->title; ?></h4>
			<div class="row">
				<div class="large-9 columns">
					<p><?php echo $user_route->description; ?></p>
				</div>
				<div class="large-3 columns">
					<a href="<?php echo $this->url->get("/route/". $user_route->id ."/".
						$this->tag->friendlyTitle($user_route->title, "-"));?>"
					   class="radius button right"><i
							class="fi-eye"></i></a>
				</div>
			</div>
		</div>

	<?php endforeach ?>

	<a class="close-reveal-modal" aria-label="Close">&#215;</a>
</div>
