<h1 class="headers-provisorios">UserController - profileAction</h1>

<?php $this->flashSession->output(); ?>

<div class="row">
	<div class="large-4 columns text-center panel">
		<div class="row text-center">
			<div class="large-6 text-left small-6 columns">
				<h4><?php echo $user_info->username; ?> </h4>
			</div>
			<div class="large-6 small-6 text-right columns">
				<i class="fi-flag"></i>
			</div>
		</div>
		<img src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim($user_info->email))); ?>?s=250">
	</div>
	<div class="large-8 columns">
		<div class="panel radius">
			<div class="row">
				<div class="large-12 columns">
					<h4><?php echo $user_info->full_name; ?></h4>
					<hr>
					<h5 class="subheader">
						<?php echo $user_info->facebook_username; ?> |
						<?php echo $user_info->twitter_username; ?> |
						<?php echo $user_info->google_plus_username; ?>
						<p>
						<?php echo $user_info->bio; ?>
						</p>
					</h5>
				</div>
			</div>
		</div>
	</div>
</div>


<div class="row panel">
	<ul class="button-group even-2">
		<li>
			<a data-reveal-id="show-user-polaroids" href="#" class="button">
				<i style="font-size: 20px;"
				   class="fi-camera"></i> Polaroids
			</a>
		</li>
		<li>
			<a data-reveal-id="show-user-routes" href="#" class="button">
				<i style="font-size: 20px;"
				   class="fi-address-book"></i> Routes
			</a>
		</li>
	</ul>
</div>

<!-- modal para as polaroids-->
<div id="show-user-polaroids" class="reveal-modal" data-reveal
     aria-labelledby="Polaroids" aria-hidden="true" role="dialog">
	<h2 class="text-center" id="Polaroids"><?php echo $user_info->username;?>'s Polaroids!</h2>

		<div class="row text-center">

		<?php $counter = 0; ?>
		<?php foreach ($user_polaroids as $user_polaroid): ?>

			<a href="<?php echo $this->url->get("/polaroid/" .
				$user_polaroid->id ."/".
				$this->tag->friendlyTitle($user_polaroid->title, "-")); ?>">
				<div class="large-3 small-12 medium-6 columns panel">
					<img src="public/img/polaroids/<?php echo $user_polaroid->photo_hash_file_name; ?>">
					<div class="panel">
						<p><?php echo $user_polaroid->title; ?> </p>
					</div>
				</div>
			</a>

			<?php
			if ($counter++ == 3 ) {
				echo "</div><div class='row'>";
				$counter = 0;
			}
			?>
		<?php endforeach ?>

	<a class="close-reveal-modal" aria-label="Close">&#215;</a>
</div>


<!-- modal para as routes -->
<div id="show-user-routes" class="reveal-modal" data-reveal
     aria-labelledby="Routes" aria-hidden="true" role="dialog">
	<h2 class="text-center" id="Routes"><?php echo $user_info->username; ?>'s Routes</h2>

	<?php foreach ($user_routes as $user_route): ?>

		<div class="panel">
			<h4><?php echo $user_route->title; ?></h4>
			<div class="row">
				<div class="large-9 columns">
					<p><?php echo $user_route->description; ?></p>
				</div>
				<div class="large-3 columns">
					<a href="<?php echo $this->url->get("/route/". $user_route->id ."/".
						$this->tag->friendlyTitle($user_route->title, "-"));?>"
					   class="radius button right"><i
							class="fi-eye"></i></a>
				</div>
			</div>
		</div>

	<?php endforeach ?>

	<a class="close-reveal-modal" aria-label="Close">&#215;</a>
</div>
