<div class="row" style="margin-top: 37px;">

<?php foreach ($user_routes as $user_route): ?>

	<div class="row panel">
		<h4><?php echo $user_route->title; ?></h4>

		<div class="row">
			<div class="large-9 columns">
				<p><?php echo $user_route->description; ?></p>
			</div>
			<div class="large-3 columns">
				<a href="<?php echo $this->url->get("/route/" . $user_route->id . "/" .
					$this->tag->friendlyTitle($user_route->title, "-")); ?>"
				   class="radius button right"><i
						class="fi-eye"></i></a>
			</div>
		</div>
	</div>

<?php endforeach ?>

</div>
