<div style="margin-top: 2em;" class="row">
    <div id="container" class="large-12 columns transitions-enabled large-centered clearfix">

<?php if (!count($user_routes)): ?>

    <div class="callout panel text-center">
        <h2>You have no routes at the moment my friend!</h2>
    </div>

<?php else: ?>

	<?php foreach ($user_routes as $user_route): ?>

		<div class="row panel">
			<h4><?php echo $user_route->title; ?></h4>

			<div class="row">
				<div class="large-9 columns">
					<p><?php echo $user_route->description; ?></p>
				</div>
				<div class="large-3 columns">
					<a href="<?php echo $this->url->get("/route/" . $user_route->id . "/" .
						$this->tag->friendlyTitle($user_route->title, "-")); ?>"
					   class="radius button right"><i
							class="fi-eye"></i></a>
				</div>
			</div>
		</div>

	<?php endforeach ?>

<?php endif ?>

	</div>
</div>
