<?php $this->flashSession->output(); ?>

<div class="row" style="margin-top: 37px;">
	<div class="large-4 columns text-center panel">
		<div class="row text-center">
			<div class="large-6 text-left small-6 columns">
				<h4><?php echo $user_info->username; ?> </h4>
			</div>
			<div class="large-6 small-6 text-right columns">
				<span class="flag-icon flag-icon-<?php echo strtolower($user_info->country); ?>"></span>
			</div>
		</div>
		<img
			src="http://www.gravatar.com/avatar/<?php echo md5(strtolower(trim($user_info->email))); ?>?s=250&d=<?php echo urlencode("http://polaroid-map-app.t.proxylocal.com/polaroid-map-app/img/misc/monster.png");?>">
	</div>
	<div class="large-8 columns">
		<div class="panel radius">
			<div class="row">
				<div class="large-12 columns text-center">
					<?php if ($user_info->full_name): ?>
						<h4><?php echo $user_info->full_name; ?></h4>
						<hr>
					<?php endif ?>
				<h5 class="subheader">
					<div class="row collapse">
						<?php if ($user_info->facebook_username): ?>
							<div class="small-12 medium-4 end columns">
								<a href="https://facebook.com/<?php echo $user_info->facebook_username; ?>">
								<img src="/polaroid-map-app/public/img/social-icons/facebook.png" alt="<?php echo $user_info->facebook_username; ?>"> Facebook
								</a>
							</div>
						<?php endif ?>
						<?php if ($user_info->twitter_username): ?>

						<div class="small-12 medium-4 end columns">
							<a href="https://twitter.com/<?php echo $user_info->twitter_username; ?>">
							<img src="/polaroid-map-app/public/img/social-icons/twitter.png" alt="<?php echo $user_info->twitter_username; ?>"> Twitter
							</a>
						</div>
						<?php endif ?>
						<?php if ($user_info->google_plus_username): ?>
						<div class="small-12 medium-4 end columns">
							<a href="https://plus.google.com/<?php echo $user_info->google_plus_username; ?>">
								<img src="/polaroid-map-app/public/img/social-icons/googleplus.png" alt="<?php echo $user_info->google_plus_username; ?>"> Google +
							</a>
						</div>
						<?php endif ?>
					</div>
				</h5>
				</div>
			</div>
		</div>
		<?php if ($user_info->bio): ?>
			<div class="panel radius text-center">
				<div class="row">
					<div class="large-12 columns text-center">
						<?php echo $user_info->bio; ?>
					</div>
				</div>
			</div>
		<?php endif ?>
	</div>
</div>


<div class="row panel">
	<ul class="button-group even-2">
		<li>
			<a data-reveal-id="show-user-polaroids" href="#" class="button">
				<i style="font-size: 20px;"
				   class="fi-camera"></i> Polaroids
			</a>
		</li>
		<li>
			<a data-reveal-id="show-user-routes" href="#" class="button">
				<i style="font-size: 20px;"
				   class="fi-address-book"></i> Routes
			</a>
		</li>
	</ul>
	<ul class="button-group even-2">
		<li>
			<a data-reveal-id="followers-modal" href="#" class="button warning">
				<i style="font-size: 20px;"
				   class="fi-social-myspace"></i> Followers <span class="label secondary alert round"><?php echo $number_of_followers; ?></span>
			</a>
		</li>
		<li>
			<a data-reveal-id="following-modal" href="#" class="button warning">
				<i style="font-size: 20px;"
				   class="fi-torsos-all"></i> Following <span class="label secondary alert round"><?php echo $number_of_following ?></span>
			</a>
		</li>
	</ul>
</div>

<!-- modal para as polaroids-->
<div id="show-user-polaroids" class="reveal-modal" data-reveal
     aria-labelledby="Polaroids" aria-hidden="true" role="dialog">
	<h2 class="text-center" id="Polaroids"><?php echo $user_info->username;
		?>'s Polaroids!</h2>

	<div style="margin-top: 2em;" class="row">
	    <div id="container" class="large-12 columns transitions-enabled large-centered clearfix">

	<?php if ($number_of_user_polaroids): ?>

	    <?php foreach ($user_polaroids as $user_polaroid): ?>
	        <div class="box col3">
            <div style="padding-top: 2px;" class="thumbnail">
                <div style="padding-left: 14px; padding-right: 14px;" class="row">
                    <div class="right">
                        <a href="<?php echo $this->url->get("/find-by-country/". strtolower($user_polaroid->country)); ?>"><span class="flag-icon flag-icon-<?php echo strtolower($user_polaroid->country); ?>"></span></a>
                    </div>
                </div>
	                <a href="<?php echo $this->url->get("/polaroid/" . $user_polaroid->id . "/" .
	            $this->tag->friendlyTitle($user_polaroid->title, "-")); ?>">
	                <img class="img-rounded BarnieFonte" src="/polaroid-map-app/public/img/polaroids/<?php echo $user_polaroid->photo_hash_file_name; ?>">
	                </a>
	                <div class="caption text-center BarnieFonte">
	                    <h3 style="font-size: 1.5em;" class="BarnieFonte"><?php echo $user_polaroid->title; ?></h3>
	                    <p style="margin-bottom: -0.75rem; border-top: 0.1px solid rgba(128, 128, 128, 0.2); padding-top: 5px;"><?php echo date("F j, Y", strtotime($user_polaroid->datetime_created)); ?></p> </div>
	            </div>
	        </div>
	    <?php endforeach ?>

	<?php else: ?>
			<p> has no polaroids yet!</p>
		    <div class="callout panel text-center">
		        <h2><?php echo $user_info->username; ?> has no polaroids!</h2>
		    </div>
	<?php endif ?>

	    </div>
	</div>
		<a class="close-reveal-modal" aria-label="Close">&#215;</a>
</div>


	<!-- modal para as routes -->
	<div id="show-user-routes" class="reveal-modal text-center" data-reveal
	     aria-labelledby="Routes" aria-hidden="true" role="dialog">
		<h2 class="text-center" id="Routes"><?php echo $user_info->username; ?>
			's Routes</h2>

		<?php if ($number_of_user_routes): ?>

			<?php foreach ($user_routes as $user_route): ?>

				<div class="panel">
					<h4><?php echo $user_route->title; ?></h4>

					<div class="row">
						<div class="large-9 columns">
							<p><?php echo $user_route->description; ?></p>
						</div>
						<div class="large-3 columns">
							<a href="<?php echo $this->url->get("/route/" . $user_route->id . "/" .
								$this->tag->friendlyTitle($user_route->title, "-")); ?>"
							   class="radius button right"><i
									class="fi-eye"></i></a>
						</div>
					</div>
				</div>

			<?php endforeach ?>

		<?php else: ?>
		    <div class="callout panel text-center">
		        <h2><?php echo $user_info->username; ?> has no routes!</h2>
		    </div>
		<?php endif ?>

		<a class="close-reveal-modal" aria-label="Close">&#215;</a>
	</div>



<!-- modal para followers -->

	<!-- modal para as routes -->
	<div id="followers-modal" class="reveal-modal text-center" data-reveal
	     aria-labelledby="Followers" aria-hidden="true" role="dialog">
		<h2 class="text-center" id="Followers"><?php echo $user_info->username; ?>'s Followers</h2>

	<div style="margin-top: 2em;" class="row">
	    <div id="container" class="large-12 columns transitions-enabled large-centered clearfix">

		<?php if (!count($followers)): ?>

		    <div class="callout panel text-center">
		        <h2><?php echo $user_info->username; ?> must be an antisocial beast!</h2>
		    </div>

		<?php else: ?>

		    <?php foreach ($followers as $f): ?>
		        <?php $follower_info = Users::findFirst($f->id_user_who_follows); ?>
		         <div class="box col3">
		            <div class="thumbnail">
		                <a href="<?php echo $this->url->get("/user/" . $follower_info->id . "/" . $this->tag->friendlyTitle($follower_info->username, "-")); ?>">
		                <img src="http://www.gravatar.com/avatar/<?php
		                 echo md5(strtolower(trim($follower_info->email))); ?>?s=280&d=<?php echo urlencode("http://polaroid-map-app.t.proxylocal.com/polaroid-map-app/img/misc/monster.png");?>">
		                </a>
		                <div class="caption text-center BarnieFonte">
		                    <h3 style="font-size: 1.5em;" class=""><?php echo $follower_info->username; ?></h3>
		                </div>
		            </div>
		        </div>
		    <?php endforeach ?>
		<?php endif ?>

		</div>
	</div>
		<a class="close-reveal-modal" aria-label="Close">&#215;</a>
</div>



<!-- modal para who user is following -->

	<!-- modal para as routes -->
	<div id="following-modal" class="reveal-modal text-center" data-reveal
	     aria-labelledby="Following" aria-hidden="true" role="dialog">
		<h2 class="text-center" id="Following"><?php echo $user_info->username; ?> is Following</h2>

	<div style="margin-top: 2em;" class="row">
	    <div id="container" class="large-12 columns transitions-enabled large-centered clearfix">

		<?php if (!count($following)): ?>

		    <div class="callout panel text-center">
		        <h2><?php echo $user_info->username; ?> is an antisocial being, because isn't following anyone <br>at the moment!</h2>
		    </div>

		<?php else: ?>

		    <?php foreach ($following as $f): ?>
		        <div class="box col3">
		            <div class="thumbnail">
		                <a href="<?php echo $this->url->get("/user/" . $f->users->id . "/" .
		            $this->tag->friendlyTitle($f->users->username, "-")); ?>">
		                <img src="http://www.gravatar.com/avatar/<?php
		                echo md5(strtolower(trim($f->users->email))); ?>?s=280&d=<?php echo urlencode("http://polaroid-map-app.t.proxylocal.com/polaroid-map-app/img/misc/monster.png");?>">
		                </a>
		                <div class="caption text-center BarnieFonte">
		                    <h3 style="font-size: 1.5em;" class=""><?php echo $f->users->username; ?></h3>
		                </div>
		            </div>
		        </div>
		    <?php endforeach ?>
		<?php endif ?>

		</div>
	</div>
		<a class="close-reveal-modal" aria-label="Close">&#215;</a>
</div>



<?php if($this->session->has("auth") && $user_info->id != $this->session->get("auth")["id"] ): ?>

	<?php if ($user_follows_user_or_not): ?>

		<div class="row panel">
				<form action="<?php echo("/polaroid-map-app/unfollow-user"); ?>"
				      method="post">

					<input type="hidden"
					       name="<?php echo $this->security->getTokenKey(); ?>"
					       value="<?php echo $this->security->getToken(); ?>">

					<input type="hidden" name="user_to_unfollow_id"
					       value="<?php echo $user_info->id;
					       ?>"/>

					<button type="submit" id="unfollowUserButton"
					        class="button expand alert round">
						<i style="font-size: 20px;"
						   class="fi-like"></i> Unfollow
					</button>
				</form>
		</div>

	<?php else: ?>

		<div class="row panel">
				<form action="<?php echo("/polaroid-map-app/follow-user"); ?>"
				      method="post">

					<input type="hidden"
					       name="<?php echo $this->security->getTokenKey(); ?>"
					       value="<?php echo $this->security->getToken(); ?>">

					<input type="hidden" name="user_to_follow_id"
					       value="<?php echo $user_info->id;
					       ?>"/>

					<button type="submit" id="followUserButton"
					        class="button expand success round">
						<i style="font-size: 20px;"
						   class="fi-like"></i> Follow
					</button>
				</form>
		</div>

	<?php endif ?>

<?php endif ?>

<?php if(!$this->session->has("auth")): ?>

	<div class="row panel text-center">
				<a href="<?php echo $this->url->get("/sign-in-up?return_to="
					. $this->router->getRewriteUri()); ?>"
				   class="button expand warning">
					<i style="font-size: 20px;"
					   class="fi-like"></i> Login to Follow <?php echo $user_info->username; ?>!
				</a>
	</div>

<?php endif ?>
