<h1 class="headers-provisorios">UserController - showAction</h1>

<?php $this->flashSession->output(); ?>

<div class="row">
	<div class="large-4 columns text-center panel">
		<div class="row text-center">
			<div class="large-6 text-left small-6 columns">
				<h4>rivalerio90</h4>
			</div>
			<div class="large-6 small-6 text-right columns">
				<i class="fi-flag"></i>
			</div>
		</div>
		<img src="http://placehold.it/250x250&amp;text=Thumbnail">
	</div>
	<div class="large-8 columns">
		<div class="panel radius">
			<div class="row">
				<div class="large-6 columns">
					<h4>Header</h4>
					<hr>
					<h5 class="subheader">Risus ligula, aliquam nec fermentum
					                      vitae, sollicitudin eget urna. Donec
					                      dignissim nibh fermentum odio ornare
					                      sagittis.</h5>
				</div>
				<div class="large-6 columns">
					<p>Suspendisse ultrices ornare tempor. Aenean eget ultricies
					   libero. Phasellus non ipsum eros. Vivamus
					   at dignissim massa. Aenean dolor libero, blandit quis
					   interdum et, malesuada nec ligula. Nullam erat
					   erat, eleifend sed pulvinar ac. Suspendisse ultrices
					   ornare tempor. Aenean eget ultricies libero.</p>
				</div>
			</div>
		</div>
	</div>
</div>


<div class="row panel">
	<ul class="button-group even-2">
		<li>
			<a data-reveal-id="show-user-polaroids" href="#" class="button">
				<i style="font-size: 20px;"
				   class="fi-camera"></i> Polaroids
			</a>
		</li>
		<li>
			<a data-reveal-id="show-user-routes" href="#" class="button">
				<i style="font-size: 20px;"
				   class="fi-address-book"></i> Routes
			</a>
		</li>
	</ul>
</div>

<!-- modal para as polaroids-->
<div id="show-user-polaroids" class="reveal-modal" data-reveal
     aria-labelledby="firstModalTitle" aria-hidden="true" role="dialog">
	<h2 id="firstModalTitle">Ricardo's Polaroids</h2>

	<div class="row">
		<div class="large-3 small-6 columns panel">
			<img src="http://placehold.it/500x500&amp;text=Thumbnail">

			<div class="panel">
				<p>Description</p>
			</div>
		</div>
		<div class="large-3 small-6 columns panel">
			<img src="http://placehold.it/500x500&amp;text=Thumbnail">

			<div class="panel">
				<p>Description</p>
			</div>
		</div>
		<div class="large-3 small-6 columns panel">
			<img src="http://placehold.it/500x500&amp;text=Thumbnail">

			<div class="panel">
				<p>Description</p>
			</div>
		</div>
		<div class="large-3 small-6 columns panel">
			<img src="http://placehold.it/500x500&amp;text=Thumbnail">

			<div class="panel">
				<p>Description</p>
			</div>
		</div>
	</div>


	<div class="row">
		<div class="large-3 small-6 columns panel">
			<img src="http://placehold.it/500x500&amp;text=Thumbnail">

			<div class="panel">
				<p>Description</p>
			</div>
		</div>
		<div class="large-3 small-6 columns panel">
			<img src="http://placehold.it/500x500&amp;text=Thumbnail">

			<div class="panel">
				<p>Description</p>
			</div>
		</div>
		<div class="large-3 small-6 columns panel">
			<img src="http://placehold.it/500x500&amp;text=Thumbnail">

			<div class="panel">
				<p>Description</p>
			</div>
		</div>
		<div class="large-3 small-6 columns panel">
			<img src="http://placehold.it/500x500&amp;text=Thumbnail">

			<div class="panel">
				<p>Description</p>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="large-3 small-6 columns panel">
			<img src="http://placehold.it/500x500&amp;text=Thumbnail">

			<div class="panel">
				<p>Description</p>
			</div>
		</div>
		<div class="large-3 small-6 columns panel">
			<img src="http://placehold.it/500x500&amp;text=Thumbnail">

			<div class="panel">
				<p>Description</p>
			</div>
		</div>
		<div class="large-3 small-6 columns panel">
			<img src="http://placehold.it/500x500&amp;text=Thumbnail">

			<div class="panel">
				<p>Description</p>
			</div>
		</div>
		<div class="large-3 small-6 columns panel">
			<img src="http://placehold.it/500x500&amp;text=Thumbnail">

			<div class="panel">
				<p>Description</p>
			</div>
		</div>
	</div>

	<a class="close-reveal-modal" aria-label="Close">&#215;</a>
</div>


<!-- modal para as routes -->
<div id="show-user-routes" class="reveal-modal" data-reveal
     aria-labelledby="firstModalTitle" aria-hidden="true" role="dialog">
	<h2 id="firstModalTitle">Ricardo's Routes</h2>

	<div class="panel">
		<h4>Get in touch!</h4>

		<div class="row">
			<div class="large-9 columns">
				<p>We'd love to hear from you, you attractive person you.</p>
			</div>
			<div class="large-3 columns">
				<a href="#" class="radius button right">Contact Us</a>
			</div>
		</div>
	</div>

	<div class="panel">
		<h4>Get in touch!</h4>

		<div class="row">
			<div class="large-9 columns">
				<p>We'd love to hear from you, you attractive person you.</p>
			</div>
			<div class="large-3 columns">
				<a href="#" class="radius button right">Contact Us</a>
			</div>
		</div>
	</div>

	<div class="panel">
		<h4>Get in touch!</h4>

		<div class="row">
			<div class="large-9 columns">
				<p>We'd love to hear from you, you attractive person you.</p>
			</div>
			<div class="large-3 columns">
				<a href="#" class="radius button right">Contact Us</a>
			</div>
		</div>
	</div>

	<a class="close-reveal-modal" aria-label="Close">&#215;</a>
</div>

<?php if ($this->session->has("auth")): ?>

	<div class="row panel">
				<a href="#" class="button expand success">
					<i style="font-size: 20px;"
					   class="fi-like"></i> Follow
				</a>
	</div>

<?php else: ?>

	<div class="row text-center">
		<ul class="button-group even-1">
			<li>
				<a href="<?php echo $this->url->get("/sign-in-up?return_to="
					. $this->router->getRewriteUri()); ?>"
				   class="button">
					<i style="font-size: 20px;"
					   class="fi-like"></i> Login to Follow!
				</a>
			</li>
		</ul>
	</div>

<?php endif ?>

