<?php echo $this->tag->getDoctype(); ?>
<html class="no-js" lang="en">
<head>
		<?php echo $this->tag->getTitle(); ?>
		<meta charset="utf-8"/>
		<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
		<!--[if lte IE 8]>
		<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
		<?php echo $this->tag->stylesheetLink("/css/normalize.css"); ?>
		<?php echo $this->tag->stylesheetLink("/css/foundation.css"); ?>
		<?php echo $this->tag->stylesheetLink("/css/foundation-icons.css"); ?>
		<?php echo $this->tag->stylesheetLink("/css/app.css"); ?>

		<?php echo $this->tag->javascriptInclude("/js/vendor/modernizr.js"); ?>
		<?php echo $this->tag->javascriptInclude("http://maps.googleapis.com/maps/api/js?v=3.exp&signed_in=true", false); ?>
</head>
	<body>

		<?php echo $this->getContent(); ?>

		<?php echo $this->tag->javascriptInclude("/js/vendor/jquery.js"); ?>
		<?php echo $this->tag->javascriptInclude("/js/foundation/foundation.min.js"); ?>
		<?php echo $this->tag->javascriptInclude("/js/foundation/foundation.abide.js"); ?>
		<?php echo $this->tag->javascriptInclude("/js/app.js"); ?>
		<script>
			$(document).foundation();
		</script>
	</body>
</html>
