<?php echo $this->tag->getDoctype(); ?>
<html class="no-js" lang="en">
<head>
		<?php echo $this->tag->getTitle(); ?>
		<meta charset="utf-8"/>
		<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
		<link rel="apple-touch-icon" sizes="57x57" href="/polaroid-map-app/apple-icon-57x57.png">
		<link rel="apple-touch-icon" sizes="60x60" href="/polaroid-map-app/apple-icon-60x60.png">
		<link rel="apple-touch-icon" sizes="72x72" href="/polaroid-map-app/apple-icon-72x72.png">
		<link rel="apple-touch-icon" sizes="76x76" href="/polaroid-map-app/apple-icon-76x76.png">
		<link rel="apple-touch-icon" sizes="114x114" href="/polaroid-map-app/apple-icon-114x114.png">
		<link rel="apple-touch-icon" sizes="120x120" href="/polaroid-map-app/apple-icon-120x120.png">
		<link rel="apple-touch-icon" sizes="144x144" href="/polaroid-map-app/apple-icon-144x144.png">
		<link rel="apple-touch-icon" sizes="152x152" href="/polaroid-map-app/apple-icon-152x152.png">
		<link rel="apple-touch-icon" sizes="180x180" href="/polaroid-map-app/apple-icon-180x180.png">
		<link rel="icon" type="image/png" sizes="192x192" href="/polaroid-map-app/android-icon-192x192.png">
		<link rel="icon" type="image/png" sizes="32x32" href="/polaroid-map-app/favicon-32x32.png">
		<link rel="icon" type="image/png" sizes="96x96" href="/polaroid-map-app/favicon-96x96.png">
		<link rel="icon" type="image/png" sizes="16x16" href="/polaroid-map-app/favicon-16x16.png">
		<link rel="manifest" href="/polaroid-map-app/manifest.json">
		<meta name="msapplication-TileColor" content="#ffffff">
		<meta name="msapplication-TileImage" content="/polaroid-map-app/ms-icon-144x144.png">
		<meta name="theme-color" content="#ffffff">

		<!--[if lte IE 8]>
		<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
		<?php echo $this->tag->stylesheetLink("/css/normalize.css"); ?>
		<?php echo $this->tag->stylesheetLink("/css/foundation.css"); ?>
		<?php echo $this->tag->stylesheetLink("/css/foundation-icons.css"); ?>
		<?php echo $this->tag->stylesheetLink("/css/app.css"); ?>

		<?php echo $this->tag->javascriptInclude("/js/vendor/modernizr.js"); ?>
		<?php if ($this->assets->collection('header')->count()): ?>
			<?php $this->assets->outputJs('header'); ?>
		<?php endif ?>

</head>
	<body>

		<?php echo $this->getContent(); ?>


		<?php echo $this->tag->javascriptInclude("/js/vendor/jquery.js"); ?>
		<?php echo $this->tag->javascriptInclude("/js/foundation/foundation.min.js"); ?>

<!--
			remover este script para os assets onde
			existe flash messages:

-->
		<?php echo $this->tag->javascriptInclude("/js/app-close-flash-messages.js"); ?>



		<?php if ($this->assets->collection('footer')->count()): ?>
			<?php $this->assets->outputJs('footer'); ?>
		<?php endif ?>

		<script>
			$(document).foundation();
		</script>

	</body>
</html>
