<?php $LOGADO = $this->session->has("auth"); ?>

<div class="off-canvas-wrap docs-wrap move-right"
     data-offcanvas="">
	<div style="height: 100%; height: 100vh;" class="inner-wrap">
		<nav class="tab-bar">
			<section class="left-small">
				<a aria-expanded="false"
				   class="left-off-canvas-toggle menu-icon"><span></span></a>
			</section>

			<section class="middle tab-bar-section">
				<div class="row collapse">
					<div style="height: 45px;" class="large-6 small-10
						columns">
								<form>
									<div class="row collapse">
										<div class="large-10 small-8 columns">
<!--					<input type="text"-->
<!--					       id="search-bar"-->
<!--					       name="search-bar"-->
<!--					       placeholder="Find polaroids, routes and people...">-->
											<?php $this->partial("partials/search-bar"); ?>
										</div>
<!--										<div class="large-2 small-3 columns">-->
<!--											<a href="#"-->
<!--											   class="postfix button expand">Search</a>-->
<!--										</div>-->
									</div>
								</form>
					</div>

					<?php if ($LOGADO): ?>
						<?php $this->partial("partials/create-polaroid-button"); ?>
					<?php else: ?>
						<?php $this->partial("partials/sign-in-up-button"); ?>
					<?php endif ?>
				</div>
			</section>

			<?php if ($LOGADO): ?>
				<section class="right-small">
					<a aria-expanded="false"
					   class="right-off-canvas-toggle menu-icon"><span></span></a>
				</section>
			<?php endif ?>
		</nav>

		<aside class="left-off-canvas-menu">
			<?php $this->partial("partials/left-side-nav"); ?>
		</aside>


		<?php if ($LOGADO): ?>
			<?php $this->partial("partials/right-side-nav"); ?>
		<?php endif ?>


		<section class="main-section">

			<?php $this->partial("partials/search-bar-results"); ?>

			<?php echo $this->getContent(); ?>

		</section>


		<!--		<a class="exit-off-canvas"></a>-->

	</div>
</div>
