<?php $LOGADO = $this->session->has("auth"); ?>

<div class="off-canvas-wrap docs-wrap move-right"
     data-offcanvas="">
	<div class="inner-wrap">
		<nav class="tab-bar">
			<section class="left-small">
				<a aria-expanded="false"
				   class="left-off-canvas-toggle menu-icon"><span></span></a>
			</section>

			<section class="middle tab-bar-section">
				<div class="row collapse">
					<div style="height: 45px;" class="large-6 small-10
						columns">
						<form class="navbar-form navbar-left" role="search">
							<div class="form-group">
								<input style="width: 75%;"
								       id="search-bar"
								       type="search"
								       name="search-bar"
								       class="form-control"
								       placeholder="Find people..."/>
							</div>
						</form>
					</div>

					<?php if ($LOGADO): ?>
						<?php $this->partial("partials/create-polaroid-button"); ?>
					<?php else: ?>
						<?php $this->partial("partials/sign-in-up-button"); ?>
					<?php endif ?>
				</div>
			</section>

			<?php if ($LOGADO): ?>
				<section class="right-small">
					<a aria-expanded="false"
					   class="right-off-canvas-toggle menu-icon"><span></span></a>
				</section>
			<?php endif ?>
		</nav>

		<aside class="left-off-canvas-menu">
			<?php $this->partial("partials/left-side-nav"); ?>
		</aside>

		<!--para quando o user está logado-->
		<?php if ($LOGADO): ?>
			<?php $this->partial("partials/right-side-nav"); ?>
		<?php endif ?>

		<section class="main-section">
			<?php echo $this->getContent(); ?>
		</section>

		<!--		<a class="exit-off-canvas"></a>-->

	</div>
</div>
