<div class="fixed">
	<nav class="top-bar" data-topbar role="navigation">
		<ul class="title-area">
			<li class="name"><h1><?php echo $this->tag->linkTo("/", "Polaroid
			Map App"); ?></h1></li>

			<!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
			<li class="toggle-topbar menu-icon"><a
					href="#"><span></span></a></li>
		</ul>
		<section class="top-bar-section">
			<!-- Right Nav Section -->
			<ul class="right">
				<li class="active"><?php echo $this->tag->linkTo("/", "Go to
				the map!"); ?></li>
				<li><a data-reveal-id="aboutModal" href="#">About</a></li>
			</ul>
		</section>
	</nav>
</div>

<!-- Reveal Modals begin -->
<div id="aboutModal" class="reveal-modal" data-reveal
     aria-labelledby="firstModalTitle" aria-hidden="true" role="dialog">
	<h2 class="text-center" id="firstModalTitle">Humans:</h2>

<div class="row text-center">
	<div class="small-12 medium-4 columns">
		<a class="th radius" href="https://github.com/rodisi">
		  <img src="https://avatars1.githubusercontent.com/u/7152174?v=3&s=200">
		</a>
		  <p>Rodisi</p>
	</div>
	<div class="small-12 medium-4 columns">
		<a class="th radius" href="https://github.com/rzZzv">
		  <img src="https://avatars2.githubusercontent.com/u/3394457?v=3&s=200">
		</a>
		  <p>RiValé</p>
	</div>
	<div class="small-12 medium-4 columns">
		<a class="th radius" href="https://github.com/rzZzv">
		  <img src="https://avatars2.githubusercontent.com/u/3394457?v=3&s=200">
		</a>
		  <p>LimoFresca</p>
	</div>
</div>

<br><br>

	<p class="text-center">
		<a href="#" data-reveal-id="moreInfoModal" class="expand button">Technologies used...</a>
	</p>

	<a class="close-reveal-modal" aria-label="Close">&#215;</a>
</div>

<div id="moreInfoModal" class="reveal-modal" data-reveal
     aria-labelledby="secondModalTitle" aria-hidden="true" role="dialog">

		<div class="row text-center" style="margin-top: 20px;">
			<div class="small-12 medium-4 columns">
				<a class="th radius" href="http://www.w3.org/TR/html5/">
				  <img src="https://avatars1.githubusercontent.com/u/1401019?v=3&s=200">
				</a>
				<p>Html5</p>
			</div>
			<div class="small-12 medium-4 columns">
				<a class="th radius" href="http://jquery.org">
				  <img src="https://avatars2.githubusercontent.com/u/70142?v=3&s=200">
				</a>
				<p>Jquery</p>
			</div>
			<div class="small-12 medium-4 columns">
				<a class="th radius" href="https://developers.google.com/maps">
				  <img src="https://avatars2.githubusercontent.com/u/3717923?v=3&s=200">
				</a>
				<p>GoogleMaps</p>
			</div>
		</div>

		<div class="row text-center" style="margin-top: 20px;">
			<div class="small-12 medium-4 columns">
				<a class="th radius" href="http://www.phalconphp.com">
				  <img src="https://avatars3.githubusercontent.com/u/1221505?v=3&s=200">
				</a>
				<p>PhalconPhp</p>
			</div>
			<div class="small-12 medium-4 columns">
				<a class="th radius" href="http://zurb.com/">
				  <img src="https://avatars3.githubusercontent.com/u/156122?v=3&s=200">
				</a>
				<p>Zurb Foundation</p>
			</div>
			<div class="small-12 medium-4 columns">
				<a class="th radius" href="http://dev.mysql.com/">
				  <img src="https://avatars0.githubusercontent.com/u/2452804?v=3&s=200">
				</a>
				<p>Mysql</p>
			</div>
		</div>


	<a class="close-reveal-modal" aria-label="Close">&#215;</a>
</div>

<?php echo $this->getContent(); ?>

