<div class="off-canvas-wrap docs-wrap move-left"
     data-offcanvas="">
	<div class="inner-wrap">
		<nav class="tab-bar">

			<section class="top-bar-section">
				<!-- Right Nav Section -->
				<ul class="left">
					<li class="active">
						<a href="<?php echo $this->url->get("/");
						?>">Mapppp!</a>
					</li>
				</ul>
			</section>

			<section class="middle tab-bar-section">
				<div class="row collapse">
					<div style="height: 45px;" class="large-6 small-10
						columns">
							<div class="row collapse">
								<div class="large-10 small-8 columns">
									<?php $this->partial("partials/search-bar"); ?>
								</div>
							</div>
					</div>

					<?php if ($this->session->has("auth")): ?>
						<?php $this->partial("partials/create-polaroid-button"); ?>
					<?php else: ?>
						<?php $this->partial("partials/sign-in-up-button"); ?>
					<?php endif ?>
				</div>
			</section>

			<?php if ($this->session->has("auth")): ?>
				<section class="right-small">
					<a aria-expanded="false"
					   class="right-off-canvas-toggle menu-icon"><span></span></a>
				</section>
			<?php endif ?>
		</nav>


		<?php if ($this->session->has("auth")): ?>
			<?php $this->partial("partials/right-side-nav"); ?>
		<?php endif ?>

		<section class="main-section">

			<?php $this->partial("partials/search-bar-results"); ?>

			<?php echo $this->getContent(); ?>

		</section>

	</div>
</div>
