<div class="off-canvas-wrap docs-wrap move-left"
     data-offcanvas="">
	<div class="inner-wrap">
		<nav class="tab-bar">

			<section class="left-small">
				<a aria-expanded="false"
				   class="left-off-canvas-toggle menu-icon"><span></span></a>
			</section>

			<section class="middle tab-bar-section">
				<div class="row collapse">
					<div style="height: 45px;" class="large-8 small-12 columns">
							<div class="row collapse">
								<div class="large-11 small-12 columns">
									<?php $this->partial("partials/search-bar"); ?>
								</div>
							</div>
					</div>

					<?php if ($this->session->has("auth")): ?>
						<?php $this->partial("partials/create-polaroid-button"); ?>
					<?php else: ?>
						<?php $this->partial("partials/sign-in-up-button"); ?>
					<?php endif ?>
				</div>
			</section>

			<?php if ($this->session->has("auth")): ?>
				<section class="right-small">
					<a aria-expanded="false"
					   class="right-off-canvas-toggle menu-icon"><span></span></a>
				</section>
			<?php endif ?>
		</nav>

		<aside class="left-off-canvas-menu">
			<?php $this->partial("partials/show-partial-left-side-nav"); ?>
		</aside>


		<?php if ($this->session->has("auth")): ?>
			<?php $this->partial("partials/right-side-nav"); ?>
		<?php endif ?>

		<section class="main-section">

			<?php $this->partial("partials/search-bar-results"); ?>

			<?php echo $this->getContent(); ?>

		</section>

	</div>
</div>
